package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class AuthToken implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_token.id
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_token.account
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_token.token
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_token.ctime
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	private Date ctime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_token.scope
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	private String scope;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_token.as_id
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	private String asId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_token.verification
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	private String verification;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_token.etime
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	private Date etime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table auth_token
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_token.id
	 * @return  the value of auth_token.id
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_token.id
	 * @param id  the value for auth_token.id
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_token.account
	 * @return  the value of auth_token.account
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_token.account
	 * @param account  the value for auth_token.account
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_token.token
	 * @return  the value of auth_token.token
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_token.token
	 * @param token  the value for auth_token.token
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_token.ctime
	 * @return  the value of auth_token.ctime
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_token.ctime
	 * @param ctime  the value for auth_token.ctime
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_token.scope
	 * @return  the value of auth_token.scope
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public String getScope() {
		return scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_token.scope
	 * @param scope  the value for auth_token.scope
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public void setScope(String scope) {
		this.scope = scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_token.as_id
	 * @return  the value of auth_token.as_id
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public String getAsId() {
		return asId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_token.as_id
	 * @param asId  the value for auth_token.as_id
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public void setAsId(String asId) {
		this.asId = asId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_token.verification
	 * @return  the value of auth_token.verification
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public String getVerification() {
		return verification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_token.verification
	 * @param verification  the value for auth_token.verification
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public void setVerification(String verification) {
		this.verification = verification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_token.etime
	 * @return  the value of auth_token.etime
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public Date getEtime() {
		return etime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_token.etime
	 * @param etime  the value for auth_token.etime
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	public void setEtime(Date etime) {
		this.etime = etime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_token
	 * @mbg.generated  Tue Jul 21 14:08:23 CST 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", account=").append(account);
		sb.append(", token=").append(token);
		sb.append(", ctime=").append(ctime);
		sb.append(", scope=").append(scope);
		sb.append(", asId=").append(asId);
		sb.append(", verification=").append(verification);
		sb.append(", etime=").append(etime);
		sb.append("]");
		return sb.toString();
	}
}