package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class ClickLog implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_log.sn
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	private Integer sn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_log.account
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_log.cnt_type
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	private String cntType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_log.cnt_id
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	private Integer cntId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_log.ctime
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	private Date ctime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_log.uid
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table click_log
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_log.sn
	 * @return  the value of click_log.sn
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public Integer getSn() {
		return sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_log.sn
	 * @param sn  the value for click_log.sn
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public void setSn(Integer sn) {
		this.sn = sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_log.account
	 * @return  the value of click_log.account
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_log.account
	 * @param account  the value for click_log.account
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_log.cnt_type
	 * @return  the value of click_log.cnt_type
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public String getCntType() {
		return cntType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_log.cnt_type
	 * @param cntType  the value for click_log.cnt_type
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public void setCntType(String cntType) {
		this.cntType = cntType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_log.cnt_id
	 * @return  the value of click_log.cnt_id
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public Integer getCntId() {
		return cntId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_log.cnt_id
	 * @param cntId  the value for click_log.cnt_id
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public void setCntId(Integer cntId) {
		this.cntId = cntId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_log.ctime
	 * @return  the value of click_log.ctime
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_log.ctime
	 * @param ctime  the value for click_log.ctime
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_log.uid
	 * @return  the value of click_log.uid
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_log.uid
	 * @param uid  the value for click_log.uid
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_log
	 * @mbg.generated  Thu Oct 12 16:04:24 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", sn=").append(sn);
		sb.append(", account=").append(account);
		sb.append(", cntType=").append(cntType);
		sb.append(", cntId=").append(cntId);
		sb.append(", ctime=").append(ctime);
		sb.append(", uid=").append(uid);
		sb.append("]");
		return sb.toString();
	}
}