package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;

public class EtdTownInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etd_town_info.id
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etd_town_info.hsn_cd
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    private String hsnCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etd_town_info.town_cd
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    private String townCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etd_town_info.town_nm
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    private String townNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etd_town_info.town_nm_en
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    private String townNmEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etd_town_info.tax_type
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    private String taxType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table etd_town_info
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etd_town_info.id
     *
     * @return the value of etd_town_info.id
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etd_town_info.id
     *
     * @param id the value for etd_town_info.id
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etd_town_info.hsn_cd
     *
     * @return the value of etd_town_info.hsn_cd
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public String getHsnCd() {
        return hsnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etd_town_info.hsn_cd
     *
     * @param hsnCd the value for etd_town_info.hsn_cd
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public void setHsnCd(String hsnCd) {
        this.hsnCd = hsnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etd_town_info.town_cd
     *
     * @return the value of etd_town_info.town_cd
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public String getTownCd() {
        return townCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etd_town_info.town_cd
     *
     * @param townCd the value for etd_town_info.town_cd
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public void setTownCd(String townCd) {
        this.townCd = townCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etd_town_info.town_nm
     *
     * @return the value of etd_town_info.town_nm
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public String getTownNm() {
        return townNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etd_town_info.town_nm
     *
     * @param townNm the value for etd_town_info.town_nm
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public void setTownNm(String townNm) {
        this.townNm = townNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etd_town_info.town_nm_en
     *
     * @return the value of etd_town_info.town_nm_en
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public String getTownNmEn() {
        return townNmEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etd_town_info.town_nm_en
     *
     * @param townNmEn the value for etd_town_info.town_nm_en
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public void setTownNmEn(String townNmEn) {
        this.townNmEn = townNmEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etd_town_info.tax_type
     *
     * @return the value of etd_town_info.tax_type
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public String getTaxType() {
        return taxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etd_town_info.tax_type
     *
     * @param taxType the value for etd_town_info.tax_type
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    public void setTaxType(String taxType) {
        this.taxType = taxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etd_town_info
     *
     * @mbg.generated Fri Dec 27 14:17:46 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", hsnCd=").append(hsnCd);
        sb.append(", townCd=").append(townCd);
        sb.append(", townNm=").append(townNm);
        sb.append(", townNmEn=").append(townNmEn);
        sb.append(", taxType=").append(taxType);
        sb.append("]");
        return sb.toString();
    }
}