package tw.gov.ndc.emsg.mydata.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PortalResourceDownloadExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	public PortalResourceDownloadExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andDownloadSnIsNull() {
			addCriterion("download_sn is null");
			return (Criteria) this;
		}

		public Criteria andDownloadSnIsNotNull() {
			addCriterion("download_sn is not null");
			return (Criteria) this;
		}

		public Criteria andDownloadSnEqualTo(String value) {
			addCriterion("download_sn =", value, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andDownloadSnNotEqualTo(String value) {
			addCriterion("download_sn <>", value, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andDownloadSnGreaterThan(String value) {
			addCriterion("download_sn >", value, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andDownloadSnGreaterThanOrEqualTo(String value) {
			addCriterion("download_sn >=", value, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andDownloadSnLessThan(String value) {
			addCriterion("download_sn <", value, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andDownloadSnLessThanOrEqualTo(String value) {
			addCriterion("download_sn <=", value, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andDownloadSnLike(String value) {
			addCriterion("download_sn like", value, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andDownloadSnNotLike(String value) {
			addCriterion("download_sn not like", value, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andDownloadSnIn(List<String> values) {
			addCriterion("download_sn in", values, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andDownloadSnNotIn(List<String> values) {
			addCriterion("download_sn not in", values, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andDownloadSnBetween(String value1, String value2) {
			addCriterion("download_sn between", value1, value2, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andDownloadSnNotBetween(String value1, String value2) {
			addCriterion("download_sn not between", value1, value2, "downloadSn");
			return (Criteria) this;
		}

		public Criteria andProviderKeyIsNull() {
			addCriterion("provider_key is null");
			return (Criteria) this;
		}

		public Criteria andProviderKeyIsNotNull() {
			addCriterion("provider_key is not null");
			return (Criteria) this;
		}

		public Criteria andProviderKeyEqualTo(String value) {
			addCriterion("provider_key =", value, "providerKey");
			return (Criteria) this;
		}

		public Criteria andProviderKeyNotEqualTo(String value) {
			addCriterion("provider_key <>", value, "providerKey");
			return (Criteria) this;
		}

		public Criteria andProviderKeyGreaterThan(String value) {
			addCriterion("provider_key >", value, "providerKey");
			return (Criteria) this;
		}

		public Criteria andProviderKeyGreaterThanOrEqualTo(String value) {
			addCriterion("provider_key >=", value, "providerKey");
			return (Criteria) this;
		}

		public Criteria andProviderKeyLessThan(String value) {
			addCriterion("provider_key <", value, "providerKey");
			return (Criteria) this;
		}

		public Criteria andProviderKeyLessThanOrEqualTo(String value) {
			addCriterion("provider_key <=", value, "providerKey");
			return (Criteria) this;
		}

		public Criteria andProviderKeyLike(String value) {
			addCriterion("provider_key like", value, "providerKey");
			return (Criteria) this;
		}

		public Criteria andProviderKeyNotLike(String value) {
			addCriterion("provider_key not like", value, "providerKey");
			return (Criteria) this;
		}

		public Criteria andProviderKeyIn(List<String> values) {
			addCriterion("provider_key in", values, "providerKey");
			return (Criteria) this;
		}

		public Criteria andProviderKeyNotIn(List<String> values) {
			addCriterion("provider_key not in", values, "providerKey");
			return (Criteria) this;
		}

		public Criteria andProviderKeyBetween(String value1, String value2) {
			addCriterion("provider_key between", value1, value2, "providerKey");
			return (Criteria) this;
		}

		public Criteria andProviderKeyNotBetween(String value1, String value2) {
			addCriterion("provider_key not between", value1, value2, "providerKey");
			return (Criteria) this;
		}

		public Criteria andPrIdIsNull() {
			addCriterion("pr_id is null");
			return (Criteria) this;
		}

		public Criteria andPrIdIsNotNull() {
			addCriterion("pr_id is not null");
			return (Criteria) this;
		}

		public Criteria andPrIdEqualTo(Integer value) {
			addCriterion("pr_id =", value, "prId");
			return (Criteria) this;
		}

		public Criteria andPrIdNotEqualTo(Integer value) {
			addCriterion("pr_id <>", value, "prId");
			return (Criteria) this;
		}

		public Criteria andPrIdGreaterThan(Integer value) {
			addCriterion("pr_id >", value, "prId");
			return (Criteria) this;
		}

		public Criteria andPrIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("pr_id >=", value, "prId");
			return (Criteria) this;
		}

		public Criteria andPrIdLessThan(Integer value) {
			addCriterion("pr_id <", value, "prId");
			return (Criteria) this;
		}

		public Criteria andPrIdLessThanOrEqualTo(Integer value) {
			addCriterion("pr_id <=", value, "prId");
			return (Criteria) this;
		}

		public Criteria andPrIdIn(List<Integer> values) {
			addCriterion("pr_id in", values, "prId");
			return (Criteria) this;
		}

		public Criteria andPrIdNotIn(List<Integer> values) {
			addCriterion("pr_id not in", values, "prId");
			return (Criteria) this;
		}

		public Criteria andPrIdBetween(Integer value1, Integer value2) {
			addCriterion("pr_id between", value1, value2, "prId");
			return (Criteria) this;
		}

		public Criteria andPrIdNotBetween(Integer value1, Integer value2) {
			addCriterion("pr_id not between", value1, value2, "prId");
			return (Criteria) this;
		}

		public Criteria andFilesIsNull() {
			addCriterion("files is null");
			return (Criteria) this;
		}

		public Criteria andFilesIsNotNull() {
			addCriterion("files is not null");
			return (Criteria) this;
		}

		public Criteria andFilesEqualTo(String value) {
			addCriterion("files =", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesNotEqualTo(String value) {
			addCriterion("files <>", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesGreaterThan(String value) {
			addCriterion("files >", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesGreaterThanOrEqualTo(String value) {
			addCriterion("files >=", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesLessThan(String value) {
			addCriterion("files <", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesLessThanOrEqualTo(String value) {
			addCriterion("files <=", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesLike(String value) {
			addCriterion("files like", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesNotLike(String value) {
			addCriterion("files not like", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesIn(List<String> values) {
			addCriterion("files in", values, "files");
			return (Criteria) this;
		}

		public Criteria andFilesNotIn(List<String> values) {
			addCriterion("files not in", values, "files");
			return (Criteria) this;
		}

		public Criteria andFilesBetween(String value1, String value2) {
			addCriterion("files between", value1, value2, "files");
			return (Criteria) this;
		}

		public Criteria andFilesNotBetween(String value1, String value2) {
			addCriterion("files not between", value1, value2, "files");
			return (Criteria) this;
		}

		public Criteria andWaitTimeIsNull() {
			addCriterion("wait_time is null");
			return (Criteria) this;
		}

		public Criteria andWaitTimeIsNotNull() {
			addCriterion("wait_time is not null");
			return (Criteria) this;
		}

		public Criteria andWaitTimeEqualTo(Integer value) {
			addCriterion("wait_time =", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeNotEqualTo(Integer value) {
			addCriterion("wait_time <>", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeGreaterThan(Integer value) {
			addCriterion("wait_time >", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("wait_time >=", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeLessThan(Integer value) {
			addCriterion("wait_time <", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeLessThanOrEqualTo(Integer value) {
			addCriterion("wait_time <=", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeIn(List<Integer> values) {
			addCriterion("wait_time in", values, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeNotIn(List<Integer> values) {
			addCriterion("wait_time not in", values, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeBetween(Integer value1, Integer value2) {
			addCriterion("wait_time between", value1, value2, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("wait_time not between", value1, value2, "waitTime");
			return (Criteria) this;
		}

		public Criteria andCtimeIsNull() {
			addCriterion("ctime is null");
			return (Criteria) this;
		}

		public Criteria andCtimeIsNotNull() {
			addCriterion("ctime is not null");
			return (Criteria) this;
		}

		public Criteria andCtimeEqualTo(Date value) {
			addCriterion("ctime =", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeNotEqualTo(Date value) {
			addCriterion("ctime <>", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeGreaterThan(Date value) {
			addCriterion("ctime >", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ctime >=", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeLessThan(Date value) {
			addCriterion("ctime <", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeLessThanOrEqualTo(Date value) {
			addCriterion("ctime <=", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeIn(List<Date> values) {
			addCriterion("ctime in", values, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeNotIn(List<Date> values) {
			addCriterion("ctime not in", values, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeBetween(Date value1, Date value2) {
			addCriterion("ctime between", value1, value2, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeNotBetween(Date value1, Date value2) {
			addCriterion("ctime not between", value1, value2, "ctime");
			return (Criteria) this;
		}

		public Criteria andStatIsNull() {
			addCriterion("stat is null");
			return (Criteria) this;
		}

		public Criteria andStatIsNotNull() {
			addCriterion("stat is not null");
			return (Criteria) this;
		}

		public Criteria andStatEqualTo(Integer value) {
			addCriterion("stat =", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatNotEqualTo(Integer value) {
			addCriterion("stat <>", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatGreaterThan(Integer value) {
			addCriterion("stat >", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatGreaterThanOrEqualTo(Integer value) {
			addCriterion("stat >=", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatLessThan(Integer value) {
			addCriterion("stat <", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatLessThanOrEqualTo(Integer value) {
			addCriterion("stat <=", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatIn(List<Integer> values) {
			addCriterion("stat in", values, "stat");
			return (Criteria) this;
		}

		public Criteria andStatNotIn(List<Integer> values) {
			addCriterion("stat not in", values, "stat");
			return (Criteria) this;
		}

		public Criteria andStatBetween(Integer value1, Integer value2) {
			addCriterion("stat between", value1, value2, "stat");
			return (Criteria) this;
		}

		public Criteria andStatNotBetween(Integer value1, Integer value2) {
			addCriterion("stat not between", value1, value2, "stat");
			return (Criteria) this;
		}

		public Criteria andDtimeIsNull() {
			addCriterion("dtime is null");
			return (Criteria) this;
		}

		public Criteria andDtimeIsNotNull() {
			addCriterion("dtime is not null");
			return (Criteria) this;
		}

		public Criteria andDtimeEqualTo(Date value) {
			addCriterion("dtime =", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeNotEqualTo(Date value) {
			addCriterion("dtime <>", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeGreaterThan(Date value) {
			addCriterion("dtime >", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("dtime >=", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeLessThan(Date value) {
			addCriterion("dtime <", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeLessThanOrEqualTo(Date value) {
			addCriterion("dtime <=", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeIn(List<Date> values) {
			addCriterion("dtime in", values, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeNotIn(List<Date> values) {
			addCriterion("dtime not in", values, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeBetween(Date value1, Date value2) {
			addCriterion("dtime between", value1, value2, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeNotBetween(Date value1, Date value2) {
			addCriterion("dtime not between", value1, value2, "dtime");
			return (Criteria) this;
		}

		public Criteria andBatchIdIsNull() {
			addCriterion("batch_id is null");
			return (Criteria) this;
		}

		public Criteria andBatchIdIsNotNull() {
			addCriterion("batch_id is not null");
			return (Criteria) this;
		}

		public Criteria andBatchIdEqualTo(Integer value) {
			addCriterion("batch_id =", value, "batchId");
			return (Criteria) this;
		}

		public Criteria andBatchIdNotEqualTo(Integer value) {
			addCriterion("batch_id <>", value, "batchId");
			return (Criteria) this;
		}

		public Criteria andBatchIdGreaterThan(Integer value) {
			addCriterion("batch_id >", value, "batchId");
			return (Criteria) this;
		}

		public Criteria andBatchIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("batch_id >=", value, "batchId");
			return (Criteria) this;
		}

		public Criteria andBatchIdLessThan(Integer value) {
			addCriterion("batch_id <", value, "batchId");
			return (Criteria) this;
		}

		public Criteria andBatchIdLessThanOrEqualTo(Integer value) {
			addCriterion("batch_id <=", value, "batchId");
			return (Criteria) this;
		}

		public Criteria andBatchIdIn(List<Integer> values) {
			addCriterion("batch_id in", values, "batchId");
			return (Criteria) this;
		}

		public Criteria andBatchIdNotIn(List<Integer> values) {
			addCriterion("batch_id not in", values, "batchId");
			return (Criteria) this;
		}

		public Criteria andBatchIdBetween(Integer value1, Integer value2) {
			addCriterion("batch_id between", value1, value2, "batchId");
			return (Criteria) this;
		}

		public Criteria andBatchIdNotBetween(Integer value1, Integer value2) {
			addCriterion("batch_id not between", value1, value2, "batchId");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andTransactionUidIsNull() {
			addCriterion("transaction_uid is null");
			return (Criteria) this;
		}

		public Criteria andTransactionUidIsNotNull() {
			addCriterion("transaction_uid is not null");
			return (Criteria) this;
		}

		public Criteria andTransactionUidEqualTo(String value) {
			addCriterion("transaction_uid =", value, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andTransactionUidNotEqualTo(String value) {
			addCriterion("transaction_uid <>", value, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andTransactionUidGreaterThan(String value) {
			addCriterion("transaction_uid >", value, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andTransactionUidGreaterThanOrEqualTo(String value) {
			addCriterion("transaction_uid >=", value, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andTransactionUidLessThan(String value) {
			addCriterion("transaction_uid <", value, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andTransactionUidLessThanOrEqualTo(String value) {
			addCriterion("transaction_uid <=", value, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andTransactionUidLike(String value) {
			addCriterion("transaction_uid like", value, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andTransactionUidNotLike(String value) {
			addCriterion("transaction_uid not like", value, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andTransactionUidIn(List<String> values) {
			addCriterion("transaction_uid in", values, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andTransactionUidNotIn(List<String> values) {
			addCriterion("transaction_uid not in", values, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andTransactionUidBetween(String value1, String value2) {
			addCriterion("transaction_uid between", value1, value2, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andTransactionUidNotBetween(String value1, String value2) {
			addCriterion("transaction_uid not between", value1, value2, "transactionUid");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeIsNull() {
			addCriterion("download_type is null");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeIsNotNull() {
			addCriterion("download_type is not null");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeEqualTo(String value) {
			addCriterion("download_type =", value, "downloadType");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeNotEqualTo(String value) {
			addCriterion("download_type <>", value, "downloadType");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeGreaterThan(String value) {
			addCriterion("download_type >", value, "downloadType");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeGreaterThanOrEqualTo(String value) {
			addCriterion("download_type >=", value, "downloadType");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeLessThan(String value) {
			addCriterion("download_type <", value, "downloadType");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeLessThanOrEqualTo(String value) {
			addCriterion("download_type <=", value, "downloadType");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeLike(String value) {
			addCriterion("download_type like", value, "downloadType");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeNotLike(String value) {
			addCriterion("download_type not like", value, "downloadType");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeIn(List<String> values) {
			addCriterion("download_type in", values, "downloadType");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeNotIn(List<String> values) {
			addCriterion("download_type not in", values, "downloadType");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeBetween(String value1, String value2) {
			addCriterion("download_type between", value1, value2, "downloadType");
			return (Criteria) this;
		}

		public Criteria andDownloadTypeNotBetween(String value1, String value2) {
			addCriterion("download_type not between", value1, value2, "downloadType");
			return (Criteria) this;
		}

		public Criteria andPreviewCountIsNull() {
			addCriterion("preview_count is null");
			return (Criteria) this;
		}

		public Criteria andPreviewCountIsNotNull() {
			addCriterion("preview_count is not null");
			return (Criteria) this;
		}

		public Criteria andPreviewCountEqualTo(Integer value) {
			addCriterion("preview_count =", value, "previewCount");
			return (Criteria) this;
		}

		public Criteria andPreviewCountNotEqualTo(Integer value) {
			addCriterion("preview_count <>", value, "previewCount");
			return (Criteria) this;
		}

		public Criteria andPreviewCountGreaterThan(Integer value) {
			addCriterion("preview_count >", value, "previewCount");
			return (Criteria) this;
		}

		public Criteria andPreviewCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("preview_count >=", value, "previewCount");
			return (Criteria) this;
		}

		public Criteria andPreviewCountLessThan(Integer value) {
			addCriterion("preview_count <", value, "previewCount");
			return (Criteria) this;
		}

		public Criteria andPreviewCountLessThanOrEqualTo(Integer value) {
			addCriterion("preview_count <=", value, "previewCount");
			return (Criteria) this;
		}

		public Criteria andPreviewCountIn(List<Integer> values) {
			addCriterion("preview_count in", values, "previewCount");
			return (Criteria) this;
		}

		public Criteria andPreviewCountNotIn(List<Integer> values) {
			addCriterion("preview_count not in", values, "previewCount");
			return (Criteria) this;
		}

		public Criteria andPreviewCountBetween(Integer value1, Integer value2) {
			addCriterion("preview_count between", value1, value2, "previewCount");
			return (Criteria) this;
		}

		public Criteria andPreviewCountNotBetween(Integer value1, Integer value2) {
			addCriterion("preview_count not between", value1, value2, "previewCount");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountIsNull() {
			addCriterion("verification_preview_count is null");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountIsNotNull() {
			addCriterion("verification_preview_count is not null");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountEqualTo(Integer value) {
			addCriterion("verification_preview_count =", value, "verificationPreviewCount");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountNotEqualTo(Integer value) {
			addCriterion("verification_preview_count <>", value, "verificationPreviewCount");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountGreaterThan(Integer value) {
			addCriterion("verification_preview_count >", value, "verificationPreviewCount");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("verification_preview_count >=", value, "verificationPreviewCount");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountLessThan(Integer value) {
			addCriterion("verification_preview_count <", value, "verificationPreviewCount");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountLessThanOrEqualTo(Integer value) {
			addCriterion("verification_preview_count <=", value, "verificationPreviewCount");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountIn(List<Integer> values) {
			addCriterion("verification_preview_count in", values, "verificationPreviewCount");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountNotIn(List<Integer> values) {
			addCriterion("verification_preview_count not in", values, "verificationPreviewCount");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountBetween(Integer value1, Integer value2) {
			addCriterion("verification_preview_count between", value1, value2, "verificationPreviewCount");
			return (Criteria) this;
		}

		public Criteria andVerificationPreviewCountNotBetween(Integer value1, Integer value2) {
			addCriterion("verification_preview_count not between", value1, value2, "verificationPreviewCount");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeIsNull() {
			addCriterion("server_download_time is null");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeIsNotNull() {
			addCriterion("server_download_time is not null");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeEqualTo(Date value) {
			addCriterion("server_download_time =", value, "serverDownloadTime");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeNotEqualTo(Date value) {
			addCriterion("server_download_time <>", value, "serverDownloadTime");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeGreaterThan(Date value) {
			addCriterion("server_download_time >", value, "serverDownloadTime");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("server_download_time >=", value, "serverDownloadTime");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeLessThan(Date value) {
			addCriterion("server_download_time <", value, "serverDownloadTime");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeLessThanOrEqualTo(Date value) {
			addCriterion("server_download_time <=", value, "serverDownloadTime");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeIn(List<Date> values) {
			addCriterion("server_download_time in", values, "serverDownloadTime");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeNotIn(List<Date> values) {
			addCriterion("server_download_time not in", values, "serverDownloadTime");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeBetween(Date value1, Date value2) {
			addCriterion("server_download_time between", value1, value2, "serverDownloadTime");
			return (Criteria) this;
		}

		public Criteria andServerDownloadTimeNotBetween(Date value1, Date value2) {
			addCriterion("server_download_time not between", value1, value2, "serverDownloadTime");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeIsNull() {
			addCriterion("download_time is null");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeIsNotNull() {
			addCriterion("download_time is not null");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeEqualTo(Date value) {
			addCriterion("download_time =", value, "downloadTime");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeNotEqualTo(Date value) {
			addCriterion("download_time <>", value, "downloadTime");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeGreaterThan(Date value) {
			addCriterion("download_time >", value, "downloadTime");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("download_time >=", value, "downloadTime");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeLessThan(Date value) {
			addCriterion("download_time <", value, "downloadTime");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeLessThanOrEqualTo(Date value) {
			addCriterion("download_time <=", value, "downloadTime");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeIn(List<Date> values) {
			addCriterion("download_time in", values, "downloadTime");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeNotIn(List<Date> values) {
			addCriterion("download_time not in", values, "downloadTime");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeBetween(Date value1, Date value2) {
			addCriterion("download_time between", value1, value2, "downloadTime");
			return (Criteria) this;
		}

		public Criteria andDownloadTimeNotBetween(Date value1, Date value2) {
			addCriterion("download_time not between", value1, value2, "downloadTime");
			return (Criteria) this;
		}

		public Criteria andRequestStatusIsNull() {
			addCriterion("request_status is null");
			return (Criteria) this;
		}

		public Criteria andRequestStatusIsNotNull() {
			addCriterion("request_status is not null");
			return (Criteria) this;
		}

		public Criteria andRequestStatusEqualTo(String value) {
			addCriterion("request_status =", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusNotEqualTo(String value) {
			addCriterion("request_status <>", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusGreaterThan(String value) {
			addCriterion("request_status >", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusGreaterThanOrEqualTo(String value) {
			addCriterion("request_status >=", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusLessThan(String value) {
			addCriterion("request_status <", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusLessThanOrEqualTo(String value) {
			addCriterion("request_status <=", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusLike(String value) {
			addCriterion("request_status like", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusNotLike(String value) {
			addCriterion("request_status not like", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusIn(List<String> values) {
			addCriterion("request_status in", values, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusNotIn(List<String> values) {
			addCriterion("request_status not in", values, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusBetween(String value1, String value2) {
			addCriterion("request_status between", value1, value2, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusNotBetween(String value1, String value2) {
			addCriterion("request_status not between", value1, value2, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeIsNull() {
			addCriterion("verification_type is null");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeIsNotNull() {
			addCriterion("verification_type is not null");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeEqualTo(String value) {
			addCriterion("verification_type =", value, "verificationType");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeNotEqualTo(String value) {
			addCriterion("verification_type <>", value, "verificationType");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeGreaterThan(String value) {
			addCriterion("verification_type >", value, "verificationType");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeGreaterThanOrEqualTo(String value) {
			addCriterion("verification_type >=", value, "verificationType");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeLessThan(String value) {
			addCriterion("verification_type <", value, "verificationType");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeLessThanOrEqualTo(String value) {
			addCriterion("verification_type <=", value, "verificationType");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeLike(String value) {
			addCriterion("verification_type like", value, "verificationType");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeNotLike(String value) {
			addCriterion("verification_type not like", value, "verificationType");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeIn(List<String> values) {
			addCriterion("verification_type in", values, "verificationType");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeNotIn(List<String> values) {
			addCriterion("verification_type not in", values, "verificationType");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeBetween(String value1, String value2) {
			addCriterion("verification_type between", value1, value2, "verificationType");
			return (Criteria) this;
		}

		public Criteria andVerificationTypeNotBetween(String value1, String value2) {
			addCriterion("verification_type not between", value1, value2, "verificationType");
			return (Criteria) this;
		}

		public Criteria andResponseTimeIsNull() {
			addCriterion("response_time is null");
			return (Criteria) this;
		}

		public Criteria andResponseTimeIsNotNull() {
			addCriterion("response_time is not null");
			return (Criteria) this;
		}

		public Criteria andResponseTimeEqualTo(Integer value) {
			addCriterion("response_time =", value, "responseTime");
			return (Criteria) this;
		}

		public Criteria andResponseTimeNotEqualTo(Integer value) {
			addCriterion("response_time <>", value, "responseTime");
			return (Criteria) this;
		}

		public Criteria andResponseTimeGreaterThan(Integer value) {
			addCriterion("response_time >", value, "responseTime");
			return (Criteria) this;
		}

		public Criteria andResponseTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("response_time >=", value, "responseTime");
			return (Criteria) this;
		}

		public Criteria andResponseTimeLessThan(Integer value) {
			addCriterion("response_time <", value, "responseTime");
			return (Criteria) this;
		}

		public Criteria andResponseTimeLessThanOrEqualTo(Integer value) {
			addCriterion("response_time <=", value, "responseTime");
			return (Criteria) this;
		}

		public Criteria andResponseTimeIn(List<Integer> values) {
			addCriterion("response_time in", values, "responseTime");
			return (Criteria) this;
		}

		public Criteria andResponseTimeNotIn(List<Integer> values) {
			addCriterion("response_time not in", values, "responseTime");
			return (Criteria) this;
		}

		public Criteria andResponseTimeBetween(Integer value1, Integer value2) {
			addCriterion("response_time between", value1, value2, "responseTime");
			return (Criteria) this;
		}

		public Criteria andResponseTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("response_time not between", value1, value2, "responseTime");
			return (Criteria) this;
		}

		public Criteria andPsdIdIsNull() {
			addCriterion("psd_id is null");
			return (Criteria) this;
		}

		public Criteria andPsdIdIsNotNull() {
			addCriterion("psd_id is not null");
			return (Criteria) this;
		}

		public Criteria andPsdIdEqualTo(Integer value) {
			addCriterion("psd_id =", value, "psdId");
			return (Criteria) this;
		}

		public Criteria andPsdIdNotEqualTo(Integer value) {
			addCriterion("psd_id <>", value, "psdId");
			return (Criteria) this;
		}

		public Criteria andPsdIdGreaterThan(Integer value) {
			addCriterion("psd_id >", value, "psdId");
			return (Criteria) this;
		}

		public Criteria andPsdIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("psd_id >=", value, "psdId");
			return (Criteria) this;
		}

		public Criteria andPsdIdLessThan(Integer value) {
			addCriterion("psd_id <", value, "psdId");
			return (Criteria) this;
		}

		public Criteria andPsdIdLessThanOrEqualTo(Integer value) {
			addCriterion("psd_id <=", value, "psdId");
			return (Criteria) this;
		}

		public Criteria andPsdIdIn(List<Integer> values) {
			addCriterion("psd_id in", values, "psdId");
			return (Criteria) this;
		}

		public Criteria andPsdIdNotIn(List<Integer> values) {
			addCriterion("psd_id not in", values, "psdId");
			return (Criteria) this;
		}

		public Criteria andPsdIdBetween(Integer value1, Integer value2) {
			addCriterion("psd_id between", value1, value2, "psdId");
			return (Criteria) this;
		}

		public Criteria andPsdIdNotBetween(Integer value1, Integer value2) {
			addCriterion("psd_id not between", value1, value2, "psdId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table portal_resource_download
	 * @mbg.generated  Mon Jun 08 15:49:20 CST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_resource_download
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 20 13:58:26 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}