package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class PortalProvider implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.provider_id
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private Integer providerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.name
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.address
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.telphone
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private String telphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.email
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.contact_info
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private String contactInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.status
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.egov_acc
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private String egovAcc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.apply_name
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private String applyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.show_all
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private Integer showAll;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.ctime
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private Date ctime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.utime
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private Date utime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.cuser
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private String cuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.uuser
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private String uuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.sp_agree_time
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private Date spAgreeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.dp_agree_time
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private Date dpAgreeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_provider.oid
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private String oid;
	
	private Integer type;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portal_provider
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.provider_id
	 * @return  the value of portal_provider.provider_id
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public Integer getProviderId() {
		return providerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.provider_id
	 * @param providerId  the value for portal_provider.provider_id
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setProviderId(Integer providerId) {
		this.providerId = providerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.name
	 * @return  the value of portal_provider.name
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.name
	 * @param name  the value for portal_provider.name
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.address
	 * @return  the value of portal_provider.address
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.address
	 * @param address  the value for portal_provider.address
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.telphone
	 * @return  the value of portal_provider.telphone
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.telphone
	 * @param telphone  the value for portal_provider.telphone
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.email
	 * @return  the value of portal_provider.email
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.email
	 * @param email  the value for portal_provider.email
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.contact_info
	 * @return  the value of portal_provider.contact_info
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public String getContactInfo() {
		return contactInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.contact_info
	 * @param contactInfo  the value for portal_provider.contact_info
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setContactInfo(String contactInfo) {
		this.contactInfo = contactInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.status
	 * @return  the value of portal_provider.status
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.status
	 * @param status  the value for portal_provider.status
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.egov_acc
	 * @return  the value of portal_provider.egov_acc
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public String getEgovAcc() {
		return egovAcc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.egov_acc
	 * @param egovAcc  the value for portal_provider.egov_acc
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setEgovAcc(String egovAcc) {
		this.egovAcc = egovAcc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.apply_name
	 * @return  the value of portal_provider.apply_name
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public String getApplyName() {
		return applyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.apply_name
	 * @param applyName  the value for portal_provider.apply_name
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setApplyName(String applyName) {
		this.applyName = applyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.show_all
	 * @return  the value of portal_provider.show_all
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public Integer getShowAll() {
		return showAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.show_all
	 * @param showAll  the value for portal_provider.show_all
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setShowAll(Integer showAll) {
		this.showAll = showAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.ctime
	 * @return  the value of portal_provider.ctime
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.ctime
	 * @param ctime  the value for portal_provider.ctime
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.utime
	 * @return  the value of portal_provider.utime
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public Date getUtime() {
		return utime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.utime
	 * @param utime  the value for portal_provider.utime
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setUtime(Date utime) {
		this.utime = utime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.cuser
	 * @return  the value of portal_provider.cuser
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public String getCuser() {
		return cuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.cuser
	 * @param cuser  the value for portal_provider.cuser
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setCuser(String cuser) {
		this.cuser = cuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.uuser
	 * @return  the value of portal_provider.uuser
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public String getUuser() {
		return uuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.uuser
	 * @param uuser  the value for portal_provider.uuser
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setUuser(String uuser) {
		this.uuser = uuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.sp_agree_time
	 * @return  the value of portal_provider.sp_agree_time
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public Date getSpAgreeTime() {
		return spAgreeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.sp_agree_time
	 * @param spAgreeTime  the value for portal_provider.sp_agree_time
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setSpAgreeTime(Date spAgreeTime) {
		this.spAgreeTime = spAgreeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.dp_agree_time
	 * @return  the value of portal_provider.dp_agree_time
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public Date getDpAgreeTime() {
		return dpAgreeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.dp_agree_time
	 * @param dpAgreeTime  the value for portal_provider.dp_agree_time
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setDpAgreeTime(Date dpAgreeTime) {
		this.dpAgreeTime = dpAgreeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_provider.oid
	 * @return  the value of portal_provider.oid
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public String getOid() {
		return oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_provider.oid
	 * @param oid  the value for portal_provider.oid
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	public void setOid(String oid) {
		this.oid = oid;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_provider
	 * @mbg.generated  Thu Jul 05 11:36:56 CST 2018
	 */
	@Override public String toString(){
		StringBuilder sb=new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");sb.append("Hash = ").append(hashCode());
		sb.append(", providerId=").append(providerId);
		sb.append(", name=").append(name);
		sb.append(", address=").append(address);
		sb.append(", telphone=").append(telphone);
		sb.append(", email=").append(email);
		sb.append(", contactInfo=").append(contactInfo);
		sb.append(", status=").append(status);
		sb.append(", egovAcc=").append(egovAcc);
		sb.append(", applyName=").append(applyName);
		sb.append(", showAll=").append(showAll);
		sb.append(", ctime=").append(ctime);
		sb.append(", utime=").append(utime);
		sb.append(", cuser=").append(cuser);
		sb.append(", uuser=").append(uuser);
		sb.append(", spAgreeTime=").append(spAgreeTime);
		sb.append(", dpAgreeTime=").append(dpAgreeTime);
		sb.append(", oid=").append(oid);
		sb.append(", type=").append(type);
		sb.append("]");
		return sb.toString();}
}