package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class PortalServiceSalt implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_salt.id
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_salt.ps_id
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    private Integer psId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_salt.tx_id
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    private String txId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_salt.salt
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_salt.ctime
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_service_salt
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_salt.id
     *
     * @return the value of portal_service_salt.id
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_salt.id
     *
     * @param id the value for portal_service_salt.id
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_salt.ps_id
     *
     * @return the value of portal_service_salt.ps_id
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    public Integer getPsId() {
        return psId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_salt.ps_id
     *
     * @param psId the value for portal_service_salt.ps_id
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    public void setPsId(Integer psId) {
        this.psId = psId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_salt.tx_id
     *
     * @return the value of portal_service_salt.tx_id
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    public String getTxId() {
        return txId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_salt.tx_id
     *
     * @param txId the value for portal_service_salt.tx_id
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    public void setTxId(String txId) {
        this.txId = txId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_salt.salt
     *
     * @return the value of portal_service_salt.salt
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_salt.salt
     *
     * @param salt the value for portal_service_salt.salt
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_salt.ctime
     *
     * @return the value of portal_service_salt.ctime
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_salt.ctime
     *
     * @param ctime the value for portal_service_salt.ctime
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_service_salt
     *
     * @mbg.generated Tue Feb 04 18:08:02 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", psId=").append(psId);
        sb.append(", txId=").append(txId);
        sb.append(", salt=").append(salt);
        sb.append(", ctime=").append(ctime);
        sb.append("]");
        return sb.toString();
    }
}