package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class PortalResourceDownload implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.download_sn
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String downloadSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.provider_key
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String providerKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.pr_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer prId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.files
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String files;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.wait_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer waitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.ctime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.stat
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer stat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.dtime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Date dtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.batch_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.email
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.code
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.transaction_uid
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String transactionUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.download_type
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String downloadType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.preview_count
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer previewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.verification_preview_count
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer verificationPreviewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.server_download_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Date serverDownloadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.download_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Date downloadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.request_status
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String requestStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.verification_type
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String verificationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.response_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer responseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.psd_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer psdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_download.digest
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String digest;

    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_resource_download
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.download_sn
     *
     * @return the value of portal_resource_download.download_sn
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getDownloadSn() {
        return downloadSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.download_sn
     *
     * @param downloadSn the value for portal_resource_download.download_sn
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setDownloadSn(String downloadSn) {
        this.downloadSn = downloadSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.provider_key
     *
     * @return the value of portal_resource_download.provider_key
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getProviderKey() {
        return providerKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.provider_key
     *
     * @param providerKey the value for portal_resource_download.provider_key
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setProviderKey(String providerKey) {
        this.providerKey = providerKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.pr_id
     *
     * @return the value of portal_resource_download.pr_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getPrId() {
        return prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.pr_id
     *
     * @param prId the value for portal_resource_download.pr_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setPrId(Integer prId) {
        this.prId = prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.files
     *
     * @return the value of portal_resource_download.files
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getFiles() {
        return files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.files
     *
     * @param files the value for portal_resource_download.files
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setFiles(String files) {
        this.files = files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.wait_time
     *
     * @return the value of portal_resource_download.wait_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getWaitTime() {
        return waitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.wait_time
     *
     * @param waitTime the value for portal_resource_download.wait_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setWaitTime(Integer waitTime) {
        this.waitTime = waitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.ctime
     *
     * @return the value of portal_resource_download.ctime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.ctime
     *
     * @param ctime the value for portal_resource_download.ctime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.stat
     *
     * @return the value of portal_resource_download.stat
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.stat
     *
     * @param stat the value for portal_resource_download.stat
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.dtime
     *
     * @return the value of portal_resource_download.dtime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Date getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.dtime
     *
     * @param dtime the value for portal_resource_download.dtime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.batch_id
     *
     * @return the value of portal_resource_download.batch_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.batch_id
     *
     * @param batchId the value for portal_resource_download.batch_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.email
     *
     * @return the value of portal_resource_download.email
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.email
     *
     * @param email the value for portal_resource_download.email
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.code
     *
     * @return the value of portal_resource_download.code
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.code
     *
     * @param code the value for portal_resource_download.code
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.transaction_uid
     *
     * @return the value of portal_resource_download.transaction_uid
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getTransactionUid() {
        return transactionUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.transaction_uid
     *
     * @param transactionUid the value for portal_resource_download.transaction_uid
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setTransactionUid(String transactionUid) {
        this.transactionUid = transactionUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.download_type
     *
     * @return the value of portal_resource_download.download_type
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getDownloadType() {
        return downloadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.download_type
     *
     * @param downloadType the value for portal_resource_download.download_type
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setDownloadType(String downloadType) {
        this.downloadType = downloadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.preview_count
     *
     * @return the value of portal_resource_download.preview_count
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getPreviewCount() {
        return previewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.preview_count
     *
     * @param previewCount the value for portal_resource_download.preview_count
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setPreviewCount(Integer previewCount) {
        this.previewCount = previewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.verification_preview_count
     *
     * @return the value of portal_resource_download.verification_preview_count
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getVerificationPreviewCount() {
        return verificationPreviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.verification_preview_count
     *
     * @param verificationPreviewCount the value for portal_resource_download.verification_preview_count
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setVerificationPreviewCount(Integer verificationPreviewCount) {
        this.verificationPreviewCount = verificationPreviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.server_download_time
     *
     * @return the value of portal_resource_download.server_download_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Date getServerDownloadTime() {
        return serverDownloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.server_download_time
     *
     * @param serverDownloadTime the value for portal_resource_download.server_download_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setServerDownloadTime(Date serverDownloadTime) {
        this.serverDownloadTime = serverDownloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.download_time
     *
     * @return the value of portal_resource_download.download_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Date getDownloadTime() {
        return downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.download_time
     *
     * @param downloadTime the value for portal_resource_download.download_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setDownloadTime(Date downloadTime) {
        this.downloadTime = downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.request_status
     *
     * @return the value of portal_resource_download.request_status
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getRequestStatus() {
        return requestStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.request_status
     *
     * @param requestStatus the value for portal_resource_download.request_status
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setRequestStatus(String requestStatus) {
        this.requestStatus = requestStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.verification_type
     *
     * @return the value of portal_resource_download.verification_type
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getVerificationType() {
        return verificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.verification_type
     *
     * @param verificationType the value for portal_resource_download.verification_type
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setVerificationType(String verificationType) {
        this.verificationType = verificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.response_time
     *
     * @return the value of portal_resource_download.response_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.response_time
     *
     * @param responseTime the value for portal_resource_download.response_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setResponseTime(Integer responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.psd_id
     *
     * @return the value of portal_resource_download.psd_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getPsdId() {
        return psdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.psd_id
     *
     * @param psdId the value for portal_resource_download.psd_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setPsdId(Integer psdId) {
        this.psdId = psdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_download.digest
     *
     * @return the value of portal_resource_download.digest
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_download.digest
     *
     * @param digest the value for portal_resource_download.digest
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setDigest(String digest) {
        this.digest = digest;
    }


    public Integer getIsShow() {
        return isShow;
    }

    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_resource_download
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", downloadSn=").append(downloadSn);
        sb.append(", providerKey=").append(providerKey);
        sb.append(", prId=").append(prId);
        sb.append(", files=").append(files);
        sb.append(", waitTime=").append(waitTime);
        sb.append(", ctime=").append(ctime);
        sb.append(", stat=").append(stat);
        sb.append(", dtime=").append(dtime);
        sb.append(", batchId=").append(batchId);
        sb.append(", email=").append(email);
        sb.append(", code=").append(code);
        sb.append(", transactionUid=").append(transactionUid);
        sb.append(", downloadType=").append(downloadType);
        sb.append(", previewCount=").append(previewCount);
        sb.append(", verificationPreviewCount=").append(verificationPreviewCount);
        sb.append(", serverDownloadTime=").append(serverDownloadTime);
        sb.append(", downloadTime=").append(downloadTime);
        sb.append(", requestStatus=").append(requestStatus);
        sb.append(", verificationType=").append(verificationType);
        sb.append(", responseTime=").append(responseTime);
        sb.append(", psdId=").append(psdId);
        sb.append(", digest=").append(digest);
        sb.append("]");
        return sb.toString();
    }
}