package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class PortalResourceMaintain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_maintain.id
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_maintain.pr_id
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    private Integer prId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_maintain.type
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_maintain.stime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    private Date stime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_maintain.etime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    private Date etime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_maintain.day
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    private Integer day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_maintain.week_day
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    private Integer weekDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_maintain.s_stime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    private Date sStime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_maintain.s_etime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    private Date sEtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_resource_maintain
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_maintain.id
     *
     * @return the value of portal_resource_maintain.id
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_maintain.id
     *
     * @param id the value for portal_resource_maintain.id
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_maintain.pr_id
     *
     * @return the value of portal_resource_maintain.pr_id
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public Integer getPrId() {
        return prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_maintain.pr_id
     *
     * @param prId the value for portal_resource_maintain.pr_id
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public void setPrId(Integer prId) {
        this.prId = prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_maintain.type
     *
     * @return the value of portal_resource_maintain.type
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_maintain.type
     *
     * @param type the value for portal_resource_maintain.type
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_maintain.stime
     *
     * @return the value of portal_resource_maintain.stime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public Date getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_maintain.stime
     *
     * @param stime the value for portal_resource_maintain.stime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public void setStime(Date stime) {
        this.stime = stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_maintain.etime
     *
     * @return the value of portal_resource_maintain.etime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public Date getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_maintain.etime
     *
     * @param etime the value for portal_resource_maintain.etime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public void setEtime(Date etime) {
        this.etime = etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_maintain.day
     *
     * @return the value of portal_resource_maintain.day
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_maintain.day
     *
     * @param day the value for portal_resource_maintain.day
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_maintain.week_day
     *
     * @return the value of portal_resource_maintain.week_day
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public Integer getWeekDay() {
        return weekDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_maintain.week_day
     *
     * @param weekDay the value for portal_resource_maintain.week_day
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public void setWeekDay(Integer weekDay) {
        this.weekDay = weekDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_maintain.s_stime
     *
     * @return the value of portal_resource_maintain.s_stime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public Date getsStime() {
        return sStime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_maintain.s_stime
     *
     * @param sStime the value for portal_resource_maintain.s_stime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public void setsStime(Date sStime) {
        this.sStime = sStime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_maintain.s_etime
     *
     * @return the value of portal_resource_maintain.s_etime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public Date getsEtime() {
        return sEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_maintain.s_etime
     *
     * @param sEtime the value for portal_resource_maintain.s_etime
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    public void setsEtime(Date sEtime) {
        this.sEtime = sEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_resource_maintain
     *
     * @mbg.generated Thu Aug 27 15:37:08 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", prId=").append(prId);
        sb.append(", type=").append(type);
        sb.append(", stime=").append(stime);
        sb.append(", etime=").append(etime);
        sb.append(", day=").append(day);
        sb.append(", weekDay=").append(weekDay);
        sb.append(", sStime=").append(sStime);
        sb.append(", sEtime=").append(sEtime);
        sb.append("]");
        return sb.toString();
    }
}