package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class PortalService implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.ps_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer psId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.client_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String clientId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.name
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.client_secret
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String clientSecret;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.redirect_uri
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String redirectUri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.logout_redirect_uri
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String logoutRedirectUri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.response_type
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String responseType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.response_mode
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String responseMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.scope
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String scope;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.brief
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String brief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.description
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.status
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.page_url
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String pageUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.agreement
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String agreement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.cate_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer cateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.provider_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer providerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.target_url
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String targetUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.ctime
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Date ctime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.etime
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Date etime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.cuser
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String cuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.service_url
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String serviceUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.agree_uri
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String agreeUri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.level
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.is_period
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer isPeriod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.period
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer period;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.uuser
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String uuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.check_stat
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer checkStat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.check_time
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Date checkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.is_show
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer isShow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.tested
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer tested;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.cbc_iv
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String cbcIv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.is_rsa
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer isRsa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.oriname
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String oriname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.customer_user
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String customerUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.prepared_document
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String preparedDocument;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.is_counter
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private Integer isCounter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.counter_description
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String counterDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.counter_prepared_document
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String counterPreparedDocument;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_service.counter_brief
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	private String counterBrief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portal_service
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */

	private Date certEdate;
	
	private Integer isOpenAgent;

	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.ps_id
	 * @return  the value of portal_service.ps_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getPsId() {
		return psId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.ps_id
	 * @param psId  the value for portal_service.ps_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setPsId(Integer psId) {
		this.psId = psId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.client_id
	 * @return  the value of portal_service.client_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getClientId() {
		return clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.client_id
	 * @param clientId  the value for portal_service.client_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.name
	 * @return  the value of portal_service.name
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.name
	 * @param name  the value for portal_service.name
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.client_secret
	 * @return  the value of portal_service.client_secret
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getClientSecret() {
		return clientSecret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.client_secret
	 * @param clientSecret  the value for portal_service.client_secret
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setClientSecret(String clientSecret) {
		this.clientSecret = clientSecret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.redirect_uri
	 * @return  the value of portal_service.redirect_uri
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getRedirectUri() {
		return redirectUri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.redirect_uri
	 * @param redirectUri  the value for portal_service.redirect_uri
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setRedirectUri(String redirectUri) {
		this.redirectUri = redirectUri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.logout_redirect_uri
	 * @return  the value of portal_service.logout_redirect_uri
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getLogoutRedirectUri() {
		return logoutRedirectUri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.logout_redirect_uri
	 * @param logoutRedirectUri  the value for portal_service.logout_redirect_uri
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setLogoutRedirectUri(String logoutRedirectUri) {
		this.logoutRedirectUri = logoutRedirectUri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.response_type
	 * @return  the value of portal_service.response_type
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getResponseType() {
		return responseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.response_type
	 * @param responseType  the value for portal_service.response_type
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setResponseType(String responseType) {
		this.responseType = responseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.response_mode
	 * @return  the value of portal_service.response_mode
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getResponseMode() {
		return responseMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.response_mode
	 * @param responseMode  the value for portal_service.response_mode
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setResponseMode(String responseMode) {
		this.responseMode = responseMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.scope
	 * @return  the value of portal_service.scope
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getScope() {
		return scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.scope
	 * @param scope  the value for portal_service.scope
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setScope(String scope) {
		this.scope = scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.brief
	 * @return  the value of portal_service.brief
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getBrief() {
		return brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.brief
	 * @param brief  the value for portal_service.brief
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setBrief(String brief) {
		this.brief = brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.description
	 * @return  the value of portal_service.description
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.description
	 * @param description  the value for portal_service.description
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.status
	 * @return  the value of portal_service.status
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.status
	 * @param status  the value for portal_service.status
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.page_url
	 * @return  the value of portal_service.page_url
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getPageUrl() {
		return pageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.page_url
	 * @param pageUrl  the value for portal_service.page_url
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setPageUrl(String pageUrl) {
		this.pageUrl = pageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.agreement
	 * @return  the value of portal_service.agreement
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getAgreement() {
		return agreement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.agreement
	 * @param agreement  the value for portal_service.agreement
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setAgreement(String agreement) {
		this.agreement = agreement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.cate_id
	 * @return  the value of portal_service.cate_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getCateId() {
		return cateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.cate_id
	 * @param cateId  the value for portal_service.cate_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setCateId(Integer cateId) {
		this.cateId = cateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.provider_id
	 * @return  the value of portal_service.provider_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getProviderId() {
		return providerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.provider_id
	 * @param providerId  the value for portal_service.provider_id
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setProviderId(Integer providerId) {
		this.providerId = providerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.target_url
	 * @return  the value of portal_service.target_url
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getTargetUrl() {
		return targetUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.target_url
	 * @param targetUrl  the value for portal_service.target_url
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setTargetUrl(String targetUrl) {
		this.targetUrl = targetUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.ctime
	 * @return  the value of portal_service.ctime
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.ctime
	 * @param ctime  the value for portal_service.ctime
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.etime
	 * @return  the value of portal_service.etime
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Date getEtime() {
		return etime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.etime
	 * @param etime  the value for portal_service.etime
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setEtime(Date etime) {
		this.etime = etime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.cuser
	 * @return  the value of portal_service.cuser
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getCuser() {
		return cuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.cuser
	 * @param cuser  the value for portal_service.cuser
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setCuser(String cuser) {
		this.cuser = cuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.service_url
	 * @return  the value of portal_service.service_url
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getServiceUrl() {
		return serviceUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.service_url
	 * @param serviceUrl  the value for portal_service.service_url
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setServiceUrl(String serviceUrl) {
		this.serviceUrl = serviceUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.agree_uri
	 * @return  the value of portal_service.agree_uri
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getAgreeUri() {
		return agreeUri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.agree_uri
	 * @param agreeUri  the value for portal_service.agree_uri
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setAgreeUri(String agreeUri) {
		this.agreeUri = agreeUri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.level
	 * @return  the value of portal_service.level
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.level
	 * @param level  the value for portal_service.level
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.is_period
	 * @return  the value of portal_service.is_period
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getIsPeriod() {
		return isPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.is_period
	 * @param isPeriod  the value for portal_service.is_period
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setIsPeriod(Integer isPeriod) {
		this.isPeriod = isPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.period
	 * @return  the value of portal_service.period
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getPeriod() {
		return period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.period
	 * @param period  the value for portal_service.period
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setPeriod(Integer period) {
		this.period = period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.uuser
	 * @return  the value of portal_service.uuser
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getUuser() {
		return uuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.uuser
	 * @param uuser  the value for portal_service.uuser
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setUuser(String uuser) {
		this.uuser = uuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.check_stat
	 * @return  the value of portal_service.check_stat
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getCheckStat() {
		return checkStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.check_stat
	 * @param checkStat  the value for portal_service.check_stat
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setCheckStat(Integer checkStat) {
		this.checkStat = checkStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.check_time
	 * @return  the value of portal_service.check_time
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Date getCheckTime() {
		return checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.check_time
	 * @param checkTime  the value for portal_service.check_time
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.is_show
	 * @return  the value of portal_service.is_show
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getIsShow() {
		return isShow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.is_show
	 * @param isShow  the value for portal_service.is_show
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.tested
	 * @return  the value of portal_service.tested
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getTested() {
		return tested;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.tested
	 * @param tested  the value for portal_service.tested
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setTested(Integer tested) {
		this.tested = tested;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.cbc_iv
	 * @return  the value of portal_service.cbc_iv
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getCbcIv() {
		return cbcIv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.cbc_iv
	 * @param cbcIv  the value for portal_service.cbc_iv
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setCbcIv(String cbcIv) {
		this.cbcIv = cbcIv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.is_rsa
	 * @return  the value of portal_service.is_rsa
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getIsRsa() {
		return isRsa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.is_rsa
	 * @param isRsa  the value for portal_service.is_rsa
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setIsRsa(Integer isRsa) {
		this.isRsa = isRsa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.oriname
	 * @return  the value of portal_service.oriname
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getOriname() {
		return oriname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.oriname
	 * @param oriname  the value for portal_service.oriname
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setOriname(String oriname) {
		this.oriname = oriname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.customer_user
	 * @return  the value of portal_service.customer_user
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getCustomerUser() {
		return customerUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.customer_user
	 * @param customerUser  the value for portal_service.customer_user
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setCustomerUser(String customerUser) {
		this.customerUser = customerUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.prepared_document
	 * @return  the value of portal_service.prepared_document
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getPreparedDocument() {
		return preparedDocument;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.prepared_document
	 * @param preparedDocument  the value for portal_service.prepared_document
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setPreparedDocument(String preparedDocument) {
		this.preparedDocument = preparedDocument;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.is_counter
	 * @return  the value of portal_service.is_counter
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public Integer getIsCounter() {
		return isCounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.is_counter
	 * @param isCounter  the value for portal_service.is_counter
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setIsCounter(Integer isCounter) {
		this.isCounter = isCounter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.counter_description
	 * @return  the value of portal_service.counter_description
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getCounterDescription() {
		return counterDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.counter_description
	 * @param counterDescription  the value for portal_service.counter_description
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setCounterDescription(String counterDescription) {
		this.counterDescription = counterDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.counter_prepared_document
	 * @return  the value of portal_service.counter_prepared_document
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getCounterPreparedDocument() {
		return counterPreparedDocument;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.counter_prepared_document
	 * @param counterPreparedDocument  the value for portal_service.counter_prepared_document
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setCounterPreparedDocument(String counterPreparedDocument) {
		this.counterPreparedDocument = counterPreparedDocument;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_service.counter_brief
	 * @return  the value of portal_service.counter_brief
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public String getCounterBrief() {
		return counterBrief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_service.counter_brief
	 * @param counterBrief  the value for portal_service.counter_brief
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	public void setCounterBrief(String counterBrief) {
		this.counterBrief = counterBrief;
	}

	public Date getCertEdate() {
		return certEdate;
	}

	public void setCertEdate(Date certEdate) {
		this.certEdate = certEdate;
	}
	
	public Integer getIsOpenAgent() {
		return isOpenAgent;
	}

	public void setIsOpenAgent(Integer isOpenAgent) {
		this.isOpenAgent = isOpenAgent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service
	 * @mbg.generated  Tue Sep 29 10:28:37 CST 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", psId=").append(psId);
		sb.append(", clientId=").append(clientId);
		sb.append(", name=").append(name);
		sb.append(", clientSecret=").append(clientSecret);
		sb.append(", redirectUri=").append(redirectUri);
		sb.append(", logoutRedirectUri=").append(logoutRedirectUri);
		sb.append(", responseType=").append(responseType);
		sb.append(", responseMode=").append(responseMode);
		sb.append(", scope=").append(scope);
		sb.append(", brief=").append(brief);
		sb.append(", description=").append(description);
		sb.append(", status=").append(status);
		sb.append(", pageUrl=").append(pageUrl);
		sb.append(", agreement=").append(agreement);
		sb.append(", cateId=").append(cateId);
		sb.append(", providerId=").append(providerId);
		sb.append(", targetUrl=").append(targetUrl);
		sb.append(", ctime=").append(ctime);
		sb.append(", etime=").append(etime);
		sb.append(", cuser=").append(cuser);
		sb.append(", serviceUrl=").append(serviceUrl);
		sb.append(", agreeUri=").append(agreeUri);
		sb.append(", level=").append(level);
		sb.append(", isPeriod=").append(isPeriod);
		sb.append(", period=").append(period);
		sb.append(", uuser=").append(uuser);
		sb.append(", checkStat=").append(checkStat);
		sb.append(", checkTime=").append(checkTime);
		sb.append(", isShow=").append(isShow);
		sb.append(", tested=").append(tested);
		sb.append(", cbcIv=").append(cbcIv);
		sb.append(", isRsa=").append(isRsa);
		sb.append(", oriname=").append(oriname);
		sb.append(", customerUser=").append(customerUser);
		sb.append(", preparedDocument=").append(preparedDocument);
		sb.append(", isCounter=").append(isCounter);
		sb.append(", counterDescription=").append(counterDescription);
		sb.append(", counterPreparedDocument=").append(counterPreparedDocument);
		sb.append(", counterBrief=").append(counterBrief);
		sb.append(", certEdate=").append(certEdate);
		sb.append(", isOpenAgent=").append(isOpenAgent);
		sb.append("]");
		return sb.toString();
	}
}