package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;

public class PortalResourceParam implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource_param.id
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource_param.pr_id
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	private Integer prId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource_param.param_name
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	private String paramName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource_param.param_desc
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	private String paramDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource_param.param_name_desc
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	private String paramNameDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource_param.default_value
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	private String defaultValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource_param.is_option
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	private Integer isOption;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portal_resource_param
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource_param.id
	 * @return  the value of portal_resource_param.id
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource_param.id
	 * @param id  the value for portal_resource_param.id
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource_param.pr_id
	 * @return  the value of portal_resource_param.pr_id
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public Integer getPrId() {
		return prId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource_param.pr_id
	 * @param prId  the value for portal_resource_param.pr_id
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public void setPrId(Integer prId) {
		this.prId = prId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource_param.param_name
	 * @return  the value of portal_resource_param.param_name
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public String getParamName() {
		return paramName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource_param.param_name
	 * @param paramName  the value for portal_resource_param.param_name
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource_param.param_desc
	 * @return  the value of portal_resource_param.param_desc
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public String getParamDesc() {
		return paramDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource_param.param_desc
	 * @param paramDesc  the value for portal_resource_param.param_desc
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public void setParamDesc(String paramDesc) {
		this.paramDesc = paramDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource_param.param_name_desc
	 * @return  the value of portal_resource_param.param_name_desc
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public String getParamNameDesc() {
		return paramNameDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource_param.param_name_desc
	 * @param paramNameDesc  the value for portal_resource_param.param_name_desc
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public void setParamNameDesc(String paramNameDesc) {
		this.paramNameDesc = paramNameDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource_param.default_value
	 * @return  the value of portal_resource_param.default_value
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public String getDefaultValue() {
		return defaultValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource_param.default_value
	 * @param defaultValue  the value for portal_resource_param.default_value
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource_param.is_option
	 * @return  the value of portal_resource_param.is_option
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public Integer getIsOption() {
		return isOption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource_param.is_option
	 * @param isOption  the value for portal_resource_param.is_option
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	public void setIsOption(Integer isOption) {
		this.isOption = isOption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource_param
	 * @mbg.generated  Fri Jul 24 13:35:19 CST 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", prId=").append(prId);
		sb.append(", paramName=").append(paramName);
		sb.append(", paramDesc=").append(paramDesc);
		sb.append(", paramNameDesc=").append(paramNameDesc);
		sb.append(", defaultValue=").append(defaultValue);
		sb.append(", isOption=").append(isOption);
		sb.append("]");
		return sb.toString();
	}
}