package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class PortalResource implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.pr_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer prId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.resource_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String resourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.name
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.resource_secret
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String resourceSecret;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.brief
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String brief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.description
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.provider_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer providerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.status
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.data_endpoint
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String dataEndpoint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.cate_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer cateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.ctime
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Date ctime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.etime
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Date etime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.cuser
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String cuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.uuser
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String uuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.fields
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String fields;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.level
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.oas_url
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String oasUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.web_url
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String webUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.period
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer period;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.period_unit
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer periodUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.download_desc
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String downloadDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.is_ftp
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer isFtp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.ftp_account
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String ftpAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.data_param
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String dataParam;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.data_send_method
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String dataSendMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.is_show
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer isShow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.data_header
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String dataHeader;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.check_stat
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer checkStat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.check_time
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Date checkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.input_param
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String inputParam;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.heartbeat_url
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String heartbeatUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.heartbeat_method
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private String heartbeatMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.moeca_check
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer moecaCheck;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.action_type
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer actionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.tested
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer tested;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.is_batch
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer isBatch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portal_resource.batch_time
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private Integer batchTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portal_resource
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.pr_id
	 * @return  the value of portal_resource.pr_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getPrId() {
		return prId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.pr_id
	 * @param prId  the value for portal_resource.pr_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setPrId(Integer prId) {
		this.prId = prId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.resource_id
	 * @return  the value of portal_resource.resource_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getResourceId() {
		return resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.resource_id
	 * @param resourceId  the value for portal_resource.resource_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.name
	 * @return  the value of portal_resource.name
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.name
	 * @param name  the value for portal_resource.name
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.resource_secret
	 * @return  the value of portal_resource.resource_secret
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getResourceSecret() {
		return resourceSecret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.resource_secret
	 * @param resourceSecret  the value for portal_resource.resource_secret
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setResourceSecret(String resourceSecret) {
		this.resourceSecret = resourceSecret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.brief
	 * @return  the value of portal_resource.brief
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getBrief() {
		return brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.brief
	 * @param brief  the value for portal_resource.brief
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setBrief(String brief) {
		this.brief = brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.description
	 * @return  the value of portal_resource.description
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.description
	 * @param description  the value for portal_resource.description
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.provider_id
	 * @return  the value of portal_resource.provider_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getProviderId() {
		return providerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.provider_id
	 * @param providerId  the value for portal_resource.provider_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setProviderId(Integer providerId) {
		this.providerId = providerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.status
	 * @return  the value of portal_resource.status
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.status
	 * @param status  the value for portal_resource.status
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.data_endpoint
	 * @return  the value of portal_resource.data_endpoint
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getDataEndpoint() {
		return dataEndpoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.data_endpoint
	 * @param dataEndpoint  the value for portal_resource.data_endpoint
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setDataEndpoint(String dataEndpoint) {
		this.dataEndpoint = dataEndpoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.cate_id
	 * @return  the value of portal_resource.cate_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getCateId() {
		return cateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.cate_id
	 * @param cateId  the value for portal_resource.cate_id
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setCateId(Integer cateId) {
		this.cateId = cateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.ctime
	 * @return  the value of portal_resource.ctime
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.ctime
	 * @param ctime  the value for portal_resource.ctime
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.etime
	 * @return  the value of portal_resource.etime
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Date getEtime() {
		return etime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.etime
	 * @param etime  the value for portal_resource.etime
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setEtime(Date etime) {
		this.etime = etime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.cuser
	 * @return  the value of portal_resource.cuser
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getCuser() {
		return cuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.cuser
	 * @param cuser  the value for portal_resource.cuser
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setCuser(String cuser) {
		this.cuser = cuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.uuser
	 * @return  the value of portal_resource.uuser
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getUuser() {
		return uuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.uuser
	 * @param uuser  the value for portal_resource.uuser
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setUuser(String uuser) {
		this.uuser = uuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.fields
	 * @return  the value of portal_resource.fields
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getFields() {
		return fields;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.fields
	 * @param fields  the value for portal_resource.fields
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setFields(String fields) {
		this.fields = fields;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.level
	 * @return  the value of portal_resource.level
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.level
	 * @param level  the value for portal_resource.level
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.oas_url
	 * @return  the value of portal_resource.oas_url
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getOasUrl() {
		return oasUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.oas_url
	 * @param oasUrl  the value for portal_resource.oas_url
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setOasUrl(String oasUrl) {
		this.oasUrl = oasUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.web_url
	 * @return  the value of portal_resource.web_url
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getWebUrl() {
		return webUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.web_url
	 * @param webUrl  the value for portal_resource.web_url
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setWebUrl(String webUrl) {
		this.webUrl = webUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.period
	 * @return  the value of portal_resource.period
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getPeriod() {
		return period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.period
	 * @param period  the value for portal_resource.period
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setPeriod(Integer period) {
		this.period = period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.period_unit
	 * @return  the value of portal_resource.period_unit
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getPeriodUnit() {
		return periodUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.period_unit
	 * @param periodUnit  the value for portal_resource.period_unit
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setPeriodUnit(Integer periodUnit) {
		this.periodUnit = periodUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.download_desc
	 * @return  the value of portal_resource.download_desc
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getDownloadDesc() {
		return downloadDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.download_desc
	 * @param downloadDesc  the value for portal_resource.download_desc
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setDownloadDesc(String downloadDesc) {
		this.downloadDesc = downloadDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.is_ftp
	 * @return  the value of portal_resource.is_ftp
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getIsFtp() {
		return isFtp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.is_ftp
	 * @param isFtp  the value for portal_resource.is_ftp
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setIsFtp(Integer isFtp) {
		this.isFtp = isFtp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.ftp_account
	 * @return  the value of portal_resource.ftp_account
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getFtpAccount() {
		return ftpAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.ftp_account
	 * @param ftpAccount  the value for portal_resource.ftp_account
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setFtpAccount(String ftpAccount) {
		this.ftpAccount = ftpAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.data_param
	 * @return  the value of portal_resource.data_param
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getDataParam() {
		return dataParam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.data_param
	 * @param dataParam  the value for portal_resource.data_param
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setDataParam(String dataParam) {
		this.dataParam = dataParam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.data_send_method
	 * @return  the value of portal_resource.data_send_method
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getDataSendMethod() {
		return dataSendMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.data_send_method
	 * @param dataSendMethod  the value for portal_resource.data_send_method
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setDataSendMethod(String dataSendMethod) {
		this.dataSendMethod = dataSendMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.is_show
	 * @return  the value of portal_resource.is_show
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getIsShow() {
		return isShow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.is_show
	 * @param isShow  the value for portal_resource.is_show
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.data_header
	 * @return  the value of portal_resource.data_header
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getDataHeader() {
		return dataHeader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.data_header
	 * @param dataHeader  the value for portal_resource.data_header
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setDataHeader(String dataHeader) {
		this.dataHeader = dataHeader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.check_stat
	 * @return  the value of portal_resource.check_stat
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getCheckStat() {
		return checkStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.check_stat
	 * @param checkStat  the value for portal_resource.check_stat
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setCheckStat(Integer checkStat) {
		this.checkStat = checkStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.check_time
	 * @return  the value of portal_resource.check_time
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Date getCheckTime() {
		return checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.check_time
	 * @param checkTime  the value for portal_resource.check_time
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.input_param
	 * @return  the value of portal_resource.input_param
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getInputParam() {
		return inputParam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.input_param
	 * @param inputParam  the value for portal_resource.input_param
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setInputParam(String inputParam) {
		this.inputParam = inputParam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.heartbeat_url
	 * @return  the value of portal_resource.heartbeat_url
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getHeartbeatUrl() {
		return heartbeatUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.heartbeat_url
	 * @param heartbeatUrl  the value for portal_resource.heartbeat_url
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setHeartbeatUrl(String heartbeatUrl) {
		this.heartbeatUrl = heartbeatUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.heartbeat_method
	 * @return  the value of portal_resource.heartbeat_method
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public String getHeartbeatMethod() {
		return heartbeatMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.heartbeat_method
	 * @param heartbeatMethod  the value for portal_resource.heartbeat_method
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setHeartbeatMethod(String heartbeatMethod) {
		this.heartbeatMethod = heartbeatMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.moeca_check
	 * @return  the value of portal_resource.moeca_check
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getMoecaCheck() {
		return moecaCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.moeca_check
	 * @param moecaCheck  the value for portal_resource.moeca_check
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setMoecaCheck(Integer moecaCheck) {
		this.moecaCheck = moecaCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.action_type
	 * @return  the value of portal_resource.action_type
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getActionType() {
		return actionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.action_type
	 * @param actionType  the value for portal_resource.action_type
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setActionType(Integer actionType) {
		this.actionType = actionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.tested
	 * @return  the value of portal_resource.tested
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getTested() {
		return tested;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.tested
	 * @param tested  the value for portal_resource.tested
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setTested(Integer tested) {
		this.tested = tested;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.is_batch
	 * @return  the value of portal_resource.is_batch
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getIsBatch() {
		return isBatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.is_batch
	 * @param isBatch  the value for portal_resource.is_batch
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setIsBatch(Integer isBatch) {
		this.isBatch = isBatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portal_resource.batch_time
	 * @return  the value of portal_resource.batch_time
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public Integer getBatchTime() {
		return batchTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portal_resource.batch_time
	 * @param batchTime  the value for portal_resource.batch_time
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	public void setBatchTime(Integer batchTime) {
		this.batchTime = batchTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_resource
	 * @mbg.generated  Wed Oct 16 11:31:23 CST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", prId=").append(prId);
		sb.append(", resourceId=").append(resourceId);
		sb.append(", name=").append(name);
		sb.append(", resourceSecret=").append(resourceSecret);
		sb.append(", brief=").append(brief);
		sb.append(", description=").append(description);
		sb.append(", providerId=").append(providerId);
		sb.append(", status=").append(status);
		sb.append(", dataEndpoint=").append(dataEndpoint);
		sb.append(", cateId=").append(cateId);
		sb.append(", ctime=").append(ctime);
		sb.append(", etime=").append(etime);
		sb.append(", cuser=").append(cuser);
		sb.append(", uuser=").append(uuser);
		sb.append(", fields=").append(fields);
		sb.append(", level=").append(level);
		sb.append(", oasUrl=").append(oasUrl);
		sb.append(", webUrl=").append(webUrl);
		sb.append(", period=").append(period);
		sb.append(", periodUnit=").append(periodUnit);
		sb.append(", downloadDesc=").append(downloadDesc);
		sb.append(", isFtp=").append(isFtp);
		sb.append(", ftpAccount=").append(ftpAccount);
		sb.append(", dataParam=").append(dataParam);
		sb.append(", dataSendMethod=").append(dataSendMethod);
		sb.append(", isShow=").append(isShow);
		sb.append(", dataHeader=").append(dataHeader);
		sb.append(", checkStat=").append(checkStat);
		sb.append(", checkTime=").append(checkTime);
		sb.append(", inputParam=").append(inputParam);
		sb.append(", heartbeatUrl=").append(heartbeatUrl);
		sb.append(", heartbeatMethod=").append(heartbeatMethod);
		sb.append(", moecaCheck=").append(moecaCheck);
		sb.append(", actionType=").append(actionType);
		sb.append(", tested=").append(tested);
		sb.append(", isBatch=").append(isBatch);
		sb.append(", batchTime=").append(batchTime);
		sb.append("]");
		return sb.toString();
	}
}