package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;

public class PortalResourceField implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_field.id
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_field.pr_id
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    private Integer prId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_field.field_name
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    private String fieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_resource_field.field_desc
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    private String fieldDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_resource_field
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_field.id
     *
     * @return the value of portal_resource_field.id
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_field.id
     *
     * @param id the value for portal_resource_field.id
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_field.pr_id
     *
     * @return the value of portal_resource_field.pr_id
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    public Integer getPrId() {
        return prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_field.pr_id
     *
     * @param prId the value for portal_resource_field.pr_id
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    public void setPrId(Integer prId) {
        this.prId = prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_field.field_name
     *
     * @return the value of portal_resource_field.field_name
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_field.field_name
     *
     * @param fieldName the value for portal_resource_field.field_name
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_resource_field.field_desc
     *
     * @return the value of portal_resource_field.field_desc
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    public String getFieldDesc() {
        return fieldDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_resource_field.field_desc
     *
     * @param fieldDesc the value for portal_resource_field.field_desc
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    public void setFieldDesc(String fieldDesc) {
        this.fieldDesc = fieldDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_resource_field
     *
     * @mbg.generated Wed Jul 25 17:26:07 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", prId=").append(prId);
        sb.append(", fieldName=").append(fieldName);
        sb.append(", fieldDesc=").append(fieldDesc);
        sb.append("]");
        return sb.toString();
    }
}