package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class PortalServiceDownload implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.ps_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer psId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.client_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.permission_ticket
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String permissionTicket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.secret_key
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String secretKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.uid
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.verification_level
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer verificationLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.download_sn_list
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String downloadSnList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.files
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String files;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.wait_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer waitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.ctime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.etime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Date etime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.dtime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Date dtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.stat
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Integer stat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.tx_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String txId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.code
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.request_status
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String requestStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.model
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.verification_type
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String verificationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.file_finish_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Date fileFinishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.download_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private Date downloadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_download.digest
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private String digest;

    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_service_download
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.id
     *
     * @return the value of portal_service_download.id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.id
     *
     * @param id the value for portal_service_download.id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.ps_id
     *
     * @return the value of portal_service_download.ps_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getPsId() {
        return psId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.ps_id
     *
     * @param psId the value for portal_service_download.ps_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setPsId(Integer psId) {
        this.psId = psId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.client_id
     *
     * @return the value of portal_service_download.client_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.client_id
     *
     * @param clientId the value for portal_service_download.client_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.permission_ticket
     *
     * @return the value of portal_service_download.permission_ticket
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getPermissionTicket() {
        return permissionTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.permission_ticket
     *
     * @param permissionTicket the value for portal_service_download.permission_ticket
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setPermissionTicket(String permissionTicket) {
        this.permissionTicket = permissionTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.secret_key
     *
     * @return the value of portal_service_download.secret_key
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.secret_key
     *
     * @param secretKey the value for portal_service_download.secret_key
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.uid
     *
     * @return the value of portal_service_download.uid
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.uid
     *
     * @param uid the value for portal_service_download.uid
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.verification_level
     *
     * @return the value of portal_service_download.verification_level
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getVerificationLevel() {
        return verificationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.verification_level
     *
     * @param verificationLevel the value for portal_service_download.verification_level
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setVerificationLevel(Integer verificationLevel) {
        this.verificationLevel = verificationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.download_sn_list
     *
     * @return the value of portal_service_download.download_sn_list
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getDownloadSnList() {
        return downloadSnList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.download_sn_list
     *
     * @param downloadSnList the value for portal_service_download.download_sn_list
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setDownloadSnList(String downloadSnList) {
        this.downloadSnList = downloadSnList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.files
     *
     * @return the value of portal_service_download.files
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getFiles() {
        return files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.files
     *
     * @param files the value for portal_service_download.files
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setFiles(String files) {
        this.files = files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.wait_time
     *
     * @return the value of portal_service_download.wait_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getWaitTime() {
        return waitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.wait_time
     *
     * @param waitTime the value for portal_service_download.wait_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setWaitTime(Integer waitTime) {
        this.waitTime = waitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.ctime
     *
     * @return the value of portal_service_download.ctime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.ctime
     *
     * @param ctime the value for portal_service_download.ctime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.etime
     *
     * @return the value of portal_service_download.etime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Date getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.etime
     *
     * @param etime the value for portal_service_download.etime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setEtime(Date etime) {
        this.etime = etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.dtime
     *
     * @return the value of portal_service_download.dtime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Date getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.dtime
     *
     * @param dtime the value for portal_service_download.dtime
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.stat
     *
     * @return the value of portal_service_download.stat
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.stat
     *
     * @param stat the value for portal_service_download.stat
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.tx_id
     *
     * @return the value of portal_service_download.tx_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getTxId() {
        return txId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.tx_id
     *
     * @param txId the value for portal_service_download.tx_id
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setTxId(String txId) {
        this.txId = txId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.code
     *
     * @return the value of portal_service_download.code
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.code
     *
     * @param code the value for portal_service_download.code
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.request_status
     *
     * @return the value of portal_service_download.request_status
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getRequestStatus() {
        return requestStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.request_status
     *
     * @param requestStatus the value for portal_service_download.request_status
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setRequestStatus(String requestStatus) {
        this.requestStatus = requestStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.model
     *
     * @return the value of portal_service_download.model
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.model
     *
     * @param model the value for portal_service_download.model
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.verification_type
     *
     * @return the value of portal_service_download.verification_type
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getVerificationType() {
        return verificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.verification_type
     *
     * @param verificationType the value for portal_service_download.verification_type
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setVerificationType(String verificationType) {
        this.verificationType = verificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.file_finish_time
     *
     * @return the value of portal_service_download.file_finish_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Date getFileFinishTime() {
        return fileFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.file_finish_time
     *
     * @param fileFinishTime the value for portal_service_download.file_finish_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setFileFinishTime(Date fileFinishTime) {
        this.fileFinishTime = fileFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.download_time
     *
     * @return the value of portal_service_download.download_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public Date getDownloadTime() {
        return downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.download_time
     *
     * @param downloadTime the value for portal_service_download.download_time
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setDownloadTime(Date downloadTime) {
        this.downloadTime = downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_download.digest
     *
     * @return the value of portal_service_download.digest
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public String getDigest() {
        return digest;
    }

    public Integer getIsShow() {
        return isShow;
    }

    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_download.digest
     *
     * @param digest the value for portal_service_download.digest
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    public void setDigest(String digest) {
        this.digest = digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_service_download
     *
     * @mbg.generated Thu Jul 02 13:46:09 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", psId=").append(psId);
        sb.append(", clientId=").append(clientId);
        sb.append(", permissionTicket=").append(permissionTicket);
        sb.append(", secretKey=").append(secretKey);
        sb.append(", uid=").append(uid);
        sb.append(", verificationLevel=").append(verificationLevel);
        sb.append(", downloadSnList=").append(downloadSnList);
        sb.append(", files=").append(files);
        sb.append(", waitTime=").append(waitTime);
        sb.append(", ctime=").append(ctime);
        sb.append(", etime=").append(etime);
        sb.append(", dtime=").append(dtime);
        sb.append(", stat=").append(stat);
        sb.append(", txId=").append(txId);
        sb.append(", code=").append(code);
        sb.append(", requestStatus=").append(requestStatus);
        sb.append(", model=").append(model);
        sb.append(", verificationType=").append(verificationType);
        sb.append(", fileFinishTime=").append(fileFinishTime);
        sb.append(", downloadTime=").append(downloadTime);
        sb.append(", digest=").append(digest);
        sb.append("]");
        return sb.toString();
    }
}