package tw.gov.ndc.emsg.mydata.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PortalServiceDownloadExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	public PortalServiceDownloadExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPsIdIsNull() {
			addCriterion("ps_id is null");
			return (Criteria) this;
		}

		public Criteria andPsIdIsNotNull() {
			addCriterion("ps_id is not null");
			return (Criteria) this;
		}

		public Criteria andPsIdEqualTo(Integer value) {
			addCriterion("ps_id =", value, "psId");
			return (Criteria) this;
		}

		public Criteria andPsIdNotEqualTo(Integer value) {
			addCriterion("ps_id <>", value, "psId");
			return (Criteria) this;
		}

		public Criteria andPsIdGreaterThan(Integer value) {
			addCriterion("ps_id >", value, "psId");
			return (Criteria) this;
		}

		public Criteria andPsIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ps_id >=", value, "psId");
			return (Criteria) this;
		}

		public Criteria andPsIdLessThan(Integer value) {
			addCriterion("ps_id <", value, "psId");
			return (Criteria) this;
		}

		public Criteria andPsIdLessThanOrEqualTo(Integer value) {
			addCriterion("ps_id <=", value, "psId");
			return (Criteria) this;
		}

		public Criteria andPsIdIn(List<Integer> values) {
			addCriterion("ps_id in", values, "psId");
			return (Criteria) this;
		}

		public Criteria andPsIdNotIn(List<Integer> values) {
			addCriterion("ps_id not in", values, "psId");
			return (Criteria) this;
		}

		public Criteria andPsIdBetween(Integer value1, Integer value2) {
			addCriterion("ps_id between", value1, value2, "psId");
			return (Criteria) this;
		}

		public Criteria andPsIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ps_id not between", value1, value2, "psId");
			return (Criteria) this;
		}

		public Criteria andClientIdIsNull() {
			addCriterion("client_id is null");
			return (Criteria) this;
		}

		public Criteria andClientIdIsNotNull() {
			addCriterion("client_id is not null");
			return (Criteria) this;
		}

		public Criteria andClientIdEqualTo(String value) {
			addCriterion("client_id =", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdNotEqualTo(String value) {
			addCriterion("client_id <>", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdGreaterThan(String value) {
			addCriterion("client_id >", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdGreaterThanOrEqualTo(String value) {
			addCriterion("client_id >=", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdLessThan(String value) {
			addCriterion("client_id <", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdLessThanOrEqualTo(String value) {
			addCriterion("client_id <=", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdLike(String value) {
			addCriterion("client_id like", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdNotLike(String value) {
			addCriterion("client_id not like", value, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdIn(List<String> values) {
			addCriterion("client_id in", values, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdNotIn(List<String> values) {
			addCriterion("client_id not in", values, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdBetween(String value1, String value2) {
			addCriterion("client_id between", value1, value2, "clientId");
			return (Criteria) this;
		}

		public Criteria andClientIdNotBetween(String value1, String value2) {
			addCriterion("client_id not between", value1, value2, "clientId");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketIsNull() {
			addCriterion("permission_ticket is null");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketIsNotNull() {
			addCriterion("permission_ticket is not null");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketEqualTo(String value) {
			addCriterion("permission_ticket =", value, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketNotEqualTo(String value) {
			addCriterion("permission_ticket <>", value, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketGreaterThan(String value) {
			addCriterion("permission_ticket >", value, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketGreaterThanOrEqualTo(String value) {
			addCriterion("permission_ticket >=", value, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketLessThan(String value) {
			addCriterion("permission_ticket <", value, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketLessThanOrEqualTo(String value) {
			addCriterion("permission_ticket <=", value, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketLike(String value) {
			addCriterion("permission_ticket like", value, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketNotLike(String value) {
			addCriterion("permission_ticket not like", value, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketIn(List<String> values) {
			addCriterion("permission_ticket in", values, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketNotIn(List<String> values) {
			addCriterion("permission_ticket not in", values, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketBetween(String value1, String value2) {
			addCriterion("permission_ticket between", value1, value2, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andPermissionTicketNotBetween(String value1, String value2) {
			addCriterion("permission_ticket not between", value1, value2, "permissionTicket");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIsNull() {
			addCriterion("secret_key is null");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIsNotNull() {
			addCriterion("secret_key is not null");
			return (Criteria) this;
		}

		public Criteria andSecretKeyEqualTo(String value) {
			addCriterion("secret_key =", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotEqualTo(String value) {
			addCriterion("secret_key <>", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyGreaterThan(String value) {
			addCriterion("secret_key >", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyGreaterThanOrEqualTo(String value) {
			addCriterion("secret_key >=", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLessThan(String value) {
			addCriterion("secret_key <", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLessThanOrEqualTo(String value) {
			addCriterion("secret_key <=", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLike(String value) {
			addCriterion("secret_key like", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotLike(String value) {
			addCriterion("secret_key not like", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIn(List<String> values) {
			addCriterion("secret_key in", values, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotIn(List<String> values) {
			addCriterion("secret_key not in", values, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyBetween(String value1, String value2) {
			addCriterion("secret_key between", value1, value2, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotBetween(String value1, String value2) {
			addCriterion("secret_key not between", value1, value2, "secretKey");
			return (Criteria) this;
		}

		public Criteria andUidIsNull() {
			addCriterion("uid is null");
			return (Criteria) this;
		}

		public Criteria andUidIsNotNull() {
			addCriterion("uid is not null");
			return (Criteria) this;
		}

		public Criteria andUidEqualTo(String value) {
			addCriterion("uid =", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotEqualTo(String value) {
			addCriterion("uid <>", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThan(String value) {
			addCriterion("uid >", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThanOrEqualTo(String value) {
			addCriterion("uid >=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThan(String value) {
			addCriterion("uid <", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThanOrEqualTo(String value) {
			addCriterion("uid <=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLike(String value) {
			addCriterion("uid like", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotLike(String value) {
			addCriterion("uid not like", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidIn(List<String> values) {
			addCriterion("uid in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotIn(List<String> values) {
			addCriterion("uid not in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidBetween(String value1, String value2) {
			addCriterion("uid between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotBetween(String value1, String value2) {
			addCriterion("uid not between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelIsNull() {
			addCriterion("verification_level is null");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelIsNotNull() {
			addCriterion("verification_level is not null");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelEqualTo(Integer value) {
			addCriterion("verification_level =", value, "verificationLevel");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelNotEqualTo(Integer value) {
			addCriterion("verification_level <>", value, "verificationLevel");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelGreaterThan(Integer value) {
			addCriterion("verification_level >", value, "verificationLevel");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("verification_level >=", value, "verificationLevel");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelLessThan(Integer value) {
			addCriterion("verification_level <", value, "verificationLevel");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelLessThanOrEqualTo(Integer value) {
			addCriterion("verification_level <=", value, "verificationLevel");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelIn(List<Integer> values) {
			addCriterion("verification_level in", values, "verificationLevel");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelNotIn(List<Integer> values) {
			addCriterion("verification_level not in", values, "verificationLevel");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelBetween(Integer value1, Integer value2) {
			addCriterion("verification_level between", value1, value2, "verificationLevel");
			return (Criteria) this;
		}

		public Criteria andVerificationLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("verification_level not between", value1, value2, "verificationLevel");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListIsNull() {
			addCriterion("download_sn_list is null");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListIsNotNull() {
			addCriterion("download_sn_list is not null");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListEqualTo(String value) {
			addCriterion("download_sn_list =", value, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListNotEqualTo(String value) {
			addCriterion("download_sn_list <>", value, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListGreaterThan(String value) {
			addCriterion("download_sn_list >", value, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListGreaterThanOrEqualTo(String value) {
			addCriterion("download_sn_list >=", value, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListLessThan(String value) {
			addCriterion("download_sn_list <", value, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListLessThanOrEqualTo(String value) {
			addCriterion("download_sn_list <=", value, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListLike(String value) {
			addCriterion("download_sn_list like", value, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListNotLike(String value) {
			addCriterion("download_sn_list not like", value, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListIn(List<String> values) {
			addCriterion("download_sn_list in", values, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListNotIn(List<String> values) {
			addCriterion("download_sn_list not in", values, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListBetween(String value1, String value2) {
			addCriterion("download_sn_list between", value1, value2, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andDownloadSnListNotBetween(String value1, String value2) {
			addCriterion("download_sn_list not between", value1, value2, "downloadSnList");
			return (Criteria) this;
		}

		public Criteria andFilesIsNull() {
			addCriterion("files is null");
			return (Criteria) this;
		}

		public Criteria andFilesIsNotNull() {
			addCriterion("files is not null");
			return (Criteria) this;
		}

		public Criteria andFilesEqualTo(String value) {
			addCriterion("files =", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesNotEqualTo(String value) {
			addCriterion("files <>", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesGreaterThan(String value) {
			addCriterion("files >", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesGreaterThanOrEqualTo(String value) {
			addCriterion("files >=", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesLessThan(String value) {
			addCriterion("files <", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesLessThanOrEqualTo(String value) {
			addCriterion("files <=", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesLike(String value) {
			addCriterion("files like", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesNotLike(String value) {
			addCriterion("files not like", value, "files");
			return (Criteria) this;
		}

		public Criteria andFilesIn(List<String> values) {
			addCriterion("files in", values, "files");
			return (Criteria) this;
		}

		public Criteria andFilesNotIn(List<String> values) {
			addCriterion("files not in", values, "files");
			return (Criteria) this;
		}

		public Criteria andFilesBetween(String value1, String value2) {
			addCriterion("files between", value1, value2, "files");
			return (Criteria) this;
		}

		public Criteria andFilesNotBetween(String value1, String value2) {
			addCriterion("files not between", value1, value2, "files");
			return (Criteria) this;
		}

		public Criteria andWaitTimeIsNull() {
			addCriterion("wait_time is null");
			return (Criteria) this;
		}

		public Criteria andWaitTimeIsNotNull() {
			addCriterion("wait_time is not null");
			return (Criteria) this;
		}

		public Criteria andWaitTimeEqualTo(Integer value) {
			addCriterion("wait_time =", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeNotEqualTo(Integer value) {
			addCriterion("wait_time <>", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeGreaterThan(Integer value) {
			addCriterion("wait_time >", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("wait_time >=", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeLessThan(Integer value) {
			addCriterion("wait_time <", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeLessThanOrEqualTo(Integer value) {
			addCriterion("wait_time <=", value, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeIn(List<Integer> values) {
			addCriterion("wait_time in", values, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeNotIn(List<Integer> values) {
			addCriterion("wait_time not in", values, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeBetween(Integer value1, Integer value2) {
			addCriterion("wait_time between", value1, value2, "waitTime");
			return (Criteria) this;
		}

		public Criteria andWaitTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("wait_time not between", value1, value2, "waitTime");
			return (Criteria) this;
		}

		public Criteria andCtimeIsNull() {
			addCriterion("ctime is null");
			return (Criteria) this;
		}

		public Criteria andCtimeIsNotNull() {
			addCriterion("ctime is not null");
			return (Criteria) this;
		}

		public Criteria andCtimeEqualTo(Date value) {
			addCriterion("ctime =", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeNotEqualTo(Date value) {
			addCriterion("ctime <>", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeGreaterThan(Date value) {
			addCriterion("ctime >", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ctime >=", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeLessThan(Date value) {
			addCriterion("ctime <", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeLessThanOrEqualTo(Date value) {
			addCriterion("ctime <=", value, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeIn(List<Date> values) {
			addCriterion("ctime in", values, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeNotIn(List<Date> values) {
			addCriterion("ctime not in", values, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeBetween(Date value1, Date value2) {
			addCriterion("ctime between", value1, value2, "ctime");
			return (Criteria) this;
		}

		public Criteria andCtimeNotBetween(Date value1, Date value2) {
			addCriterion("ctime not between", value1, value2, "ctime");
			return (Criteria) this;
		}

		public Criteria andEtimeIsNull() {
			addCriterion("etime is null");
			return (Criteria) this;
		}

		public Criteria andEtimeIsNotNull() {
			addCriterion("etime is not null");
			return (Criteria) this;
		}

		public Criteria andEtimeEqualTo(Date value) {
			addCriterion("etime =", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeNotEqualTo(Date value) {
			addCriterion("etime <>", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeGreaterThan(Date value) {
			addCriterion("etime >", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("etime >=", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeLessThan(Date value) {
			addCriterion("etime <", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeLessThanOrEqualTo(Date value) {
			addCriterion("etime <=", value, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeIn(List<Date> values) {
			addCriterion("etime in", values, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeNotIn(List<Date> values) {
			addCriterion("etime not in", values, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeBetween(Date value1, Date value2) {
			addCriterion("etime between", value1, value2, "etime");
			return (Criteria) this;
		}

		public Criteria andEtimeNotBetween(Date value1, Date value2) {
			addCriterion("etime not between", value1, value2, "etime");
			return (Criteria) this;
		}

		public Criteria andDtimeIsNull() {
			addCriterion("dtime is null");
			return (Criteria) this;
		}

		public Criteria andDtimeIsNotNull() {
			addCriterion("dtime is not null");
			return (Criteria) this;
		}

		public Criteria andDtimeEqualTo(Date value) {
			addCriterion("dtime =", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeNotEqualTo(Date value) {
			addCriterion("dtime <>", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeGreaterThan(Date value) {
			addCriterion("dtime >", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("dtime >=", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeLessThan(Date value) {
			addCriterion("dtime <", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeLessThanOrEqualTo(Date value) {
			addCriterion("dtime <=", value, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeIn(List<Date> values) {
			addCriterion("dtime in", values, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeNotIn(List<Date> values) {
			addCriterion("dtime not in", values, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeBetween(Date value1, Date value2) {
			addCriterion("dtime between", value1, value2, "dtime");
			return (Criteria) this;
		}

		public Criteria andDtimeNotBetween(Date value1, Date value2) {
			addCriterion("dtime not between", value1, value2, "dtime");
			return (Criteria) this;
		}

		public Criteria andStatIsNull() {
			addCriterion("stat is null");
			return (Criteria) this;
		}

		public Criteria andStatIsNotNull() {
			addCriterion("stat is not null");
			return (Criteria) this;
		}

		public Criteria andStatEqualTo(Integer value) {
			addCriterion("stat =", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatNotEqualTo(Integer value) {
			addCriterion("stat <>", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatGreaterThan(Integer value) {
			addCriterion("stat >", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatGreaterThanOrEqualTo(Integer value) {
			addCriterion("stat >=", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatLessThan(Integer value) {
			addCriterion("stat <", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatLessThanOrEqualTo(Integer value) {
			addCriterion("stat <=", value, "stat");
			return (Criteria) this;
		}

		public Criteria andStatIn(List<Integer> values) {
			addCriterion("stat in", values, "stat");
			return (Criteria) this;
		}

		public Criteria andStatNotIn(List<Integer> values) {
			addCriterion("stat not in", values, "stat");
			return (Criteria) this;
		}

		public Criteria andStatBetween(Integer value1, Integer value2) {
			addCriterion("stat between", value1, value2, "stat");
			return (Criteria) this;
		}

		public Criteria andStatNotBetween(Integer value1, Integer value2) {
			addCriterion("stat not between", value1, value2, "stat");
			return (Criteria) this;
		}

		public Criteria andTxIdIsNull() {
			addCriterion("tx_id is null");
			return (Criteria) this;
		}

		public Criteria andTxIdIsNotNull() {
			addCriterion("tx_id is not null");
			return (Criteria) this;
		}

		public Criteria andTxIdEqualTo(String value) {
			addCriterion("tx_id =", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdNotEqualTo(String value) {
			addCriterion("tx_id <>", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdGreaterThan(String value) {
			addCriterion("tx_id >", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdGreaterThanOrEqualTo(String value) {
			addCriterion("tx_id >=", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdLessThan(String value) {
			addCriterion("tx_id <", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdLessThanOrEqualTo(String value) {
			addCriterion("tx_id <=", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdLike(String value) {
			addCriterion("tx_id like", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdNotLike(String value) {
			addCriterion("tx_id not like", value, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdIn(List<String> values) {
			addCriterion("tx_id in", values, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdNotIn(List<String> values) {
			addCriterion("tx_id not in", values, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdBetween(String value1, String value2) {
			addCriterion("tx_id between", value1, value2, "txId");
			return (Criteria) this;
		}

		public Criteria andTxIdNotBetween(String value1, String value2) {
			addCriterion("tx_id not between", value1, value2, "txId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table portal_service_download
	 * @mbg.generated  Thu Nov 21 14:29:21 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_service_download
     *
     * @mbg.generated do_not_delete_during_merge Thu May 23 11:35:03 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}