package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class PortalServiceScopeCounter implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_scope_counter.id
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_scope_counter.scope
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_scope_counter.ps_id
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    private Integer psId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_scope_counter.status
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_service_scope_counter.ctime
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_service_scope_counter
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_scope_counter.id
     *
     * @return the value of portal_service_scope_counter.id
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_scope_counter.id
     *
     * @param id the value for portal_service_scope_counter.id
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_scope_counter.scope
     *
     * @return the value of portal_service_scope_counter.scope
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_scope_counter.scope
     *
     * @param scope the value for portal_service_scope_counter.scope
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    public void setScope(String scope) {
        this.scope = scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_scope_counter.ps_id
     *
     * @return the value of portal_service_scope_counter.ps_id
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    public Integer getPsId() {
        return psId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_scope_counter.ps_id
     *
     * @param psId the value for portal_service_scope_counter.ps_id
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    public void setPsId(Integer psId) {
        this.psId = psId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_scope_counter.status
     *
     * @return the value of portal_service_scope_counter.status
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_scope_counter.status
     *
     * @param status the value for portal_service_scope_counter.status
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_service_scope_counter.ctime
     *
     * @return the value of portal_service_scope_counter.ctime
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_service_scope_counter.ctime
     *
     * @param ctime the value for portal_service_scope_counter.ctime
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_service_scope_counter
     *
     * @mbg.generated Tue Sep 29 10:28:37 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", scope=").append(scope);
        sb.append(", psId=").append(psId);
        sb.append(", status=").append(status);
        sb.append(", ctime=").append(ctime);
        sb.append("]");
        return sb.toString();
    }
}