package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class Ulog implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog.seq
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	private Integer seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog.uid
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog.action
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	private String action;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog.action_text
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	private String actionText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog.client_id
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	private String clientId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog.scope
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	private String scope;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog.ctime
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	private Date ctime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ulog
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog.seq
	 * @return  the value of ulog.seq
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public Integer getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog.seq
	 * @param seq  the value for ulog.seq
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog.uid
	 * @return  the value of ulog.uid
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog.uid
	 * @param uid  the value for ulog.uid
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog.action
	 * @return  the value of ulog.action
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public String getAction() {
		return action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog.action
	 * @param action  the value for ulog.action
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog.action_text
	 * @return  the value of ulog.action_text
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public String getActionText() {
		return actionText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog.action_text
	 * @param actionText  the value for ulog.action_text
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public void setActionText(String actionText) {
		this.actionText = actionText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog.client_id
	 * @return  the value of ulog.client_id
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public String getClientId() {
		return clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog.client_id
	 * @param clientId  the value for ulog.client_id
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog.scope
	 * @return  the value of ulog.scope
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public String getScope() {
		return scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog.scope
	 * @param scope  the value for ulog.scope
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public void setScope(String scope) {
		this.scope = scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog.ctime
	 * @return  the value of ulog.ctime
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog.ctime
	 * @param ctime  the value for ulog.ctime
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ulog
	 * @mbg.generated  Thu Jul 05 11:36:57 CST 2018
	 */@Override public String toString(){StringBuilder sb=new StringBuilder();sb.append(getClass().getSimpleName());sb.append(" [");sb.append("Hash = ").append(hashCode());sb.append(", seq=").append(seq);sb.append(", uid=").append(uid);sb.append(", action=").append(action);sb.append(", actionText=").append(actionText);sb.append(", clientId=").append(clientId);sb.append(", scope=").append(scope);sb.append(", ctime=").append(ctime);sb.append("]");return sb.toString();}
}