package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class UlogApi implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.provider_key
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private String providerKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.user_name
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.uid
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.action
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private String action;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.action_text
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private String actionText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.client_id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private String clientId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.resource_id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private String resourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.audit_event
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private Integer auditEvent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.scope
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private String scope;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.ctime
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private Date ctime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.ip
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.encrypted
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private Boolean encrypted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.tx_id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private String txId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulog_api.transaction_uid
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private String transactionUid;

	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ulog_api
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.id
	 * @return  the value of ulog_api.id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.id
	 * @param id  the value for ulog_api.id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.provider_key
	 * @return  the value of ulog_api.provider_key
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public String getProviderKey() {
		return providerKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.provider_key
	 * @param providerKey  the value for ulog_api.provider_key
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setProviderKey(String providerKey) {
		this.providerKey = providerKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.user_name
	 * @return  the value of ulog_api.user_name
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.user_name
	 * @param userName  the value for ulog_api.user_name
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.uid
	 * @return  the value of ulog_api.uid
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.uid
	 * @param uid  the value for ulog_api.uid
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.action
	 * @return  the value of ulog_api.action
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public String getAction() {
		return action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.action
	 * @param action  the value for ulog_api.action
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.action_text
	 * @return  the value of ulog_api.action_text
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public String getActionText() {
		return actionText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.action_text
	 * @param actionText  the value for ulog_api.action_text
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setActionText(String actionText) {
		this.actionText = actionText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.client_id
	 * @return  the value of ulog_api.client_id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public String getClientId() {
		return clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.client_id
	 * @param clientId  the value for ulog_api.client_id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.resource_id
	 * @return  the value of ulog_api.resource_id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public String getResourceId() {
		return resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.resource_id
	 * @param resourceId  the value for ulog_api.resource_id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.audit_event
	 * @return  the value of ulog_api.audit_event
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public Integer getAuditEvent() {
		return auditEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.audit_event
	 * @param auditEvent  the value for ulog_api.audit_event
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setAuditEvent(Integer auditEvent) {
		this.auditEvent = auditEvent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.scope
	 * @return  the value of ulog_api.scope
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public String getScope() {
		return scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.scope
	 * @param scope  the value for ulog_api.scope
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setScope(String scope) {
		this.scope = scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.ctime
	 * @return  the value of ulog_api.ctime
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.ctime
	 * @param ctime  the value for ulog_api.ctime
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.ip
	 * @return  the value of ulog_api.ip
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.ip
	 * @param ip  the value for ulog_api.ip
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.encrypted
	 * @return  the value of ulog_api.encrypted
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public Boolean getEncrypted() {
		return encrypted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.encrypted
	 * @param encrypted  the value for ulog_api.encrypted
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setEncrypted(Boolean encrypted) {
		this.encrypted = encrypted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.tx_id
	 * @return  the value of ulog_api.tx_id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public String getTxId() {
		return txId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.tx_id
	 * @param txId  the value for ulog_api.tx_id
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setTxId(String txId) {
		this.txId = txId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulog_api.transaction_uid
	 * @return  the value of ulog_api.transaction_uid
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public String getTransactionUid() {
		return transactionUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulog_api.transaction_uid
	 * @param transactionUid  the value for ulog_api.transaction_uid
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	public void setTransactionUid(String transactionUid) {
		this.transactionUid = transactionUid;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ulog_api
	 * @mbg.generated  Wed Feb 26 16:03:18 CST 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", providerKey=").append(providerKey);
		sb.append(", userName=").append(userName);
		sb.append(", uid=").append(uid);
		sb.append(", action=").append(action);
		sb.append(", actionText=").append(actionText);
		sb.append(", clientId=").append(clientId);
		sb.append(", resourceId=").append(resourceId);
		sb.append(", auditEvent=").append(auditEvent);
		sb.append(", scope=").append(scope);
		sb.append(", ctime=").append(ctime);
		sb.append(", ip=").append(ip);
		sb.append(", encrypted=").append(encrypted);
		sb.append(", txId=").append(txId);
		sb.append(", transactionUid=").append(transactionUid);
		sb.append("]");
		return sb.toString();
	}
}