package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class VerificationLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification_log.id
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification_log.account
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification_log.type
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification_log.verification_type
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    private String verificationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification_log.ctime
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verification_log.status
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    private Integer status;

    private String signature;

    private Integer isDoubleVerify;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table verification_log
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification_log.id
     *
     * @return the value of verification_log.id
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification_log.id
     *
     * @param id the value for verification_log.id
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification_log.account
     *
     * @return the value of verification_log.account
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification_log.account
     *
     * @param account the value for verification_log.account
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification_log.type
     *
     * @return the value of verification_log.type
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification_log.type
     *
     * @param type the value for verification_log.type
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification_log.verification_type
     *
     * @return the value of verification_log.verification_type
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public String getVerificationType() {
        return verificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification_log.verification_type
     *
     * @param verificationType the value for verification_log.verification_type
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public void setVerificationType(String verificationType) {
        this.verificationType = verificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification_log.ctime
     *
     * @return the value of verification_log.ctime
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification_log.ctime
     *
     * @param ctime the value for verification_log.ctime
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verification_log.status
     *
     * @return the value of verification_log.status
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verification_log.status
     *
     * @param status the value for verification_log.status
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

    public Integer getIsDoubleVerify() {
        return isDoubleVerify;
    }

    public void setIsDoubleVerify(Integer isDoubleVerify) {
        this.isDoubleVerify = isDoubleVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_log
     *
     * @mbg.generated Wed May 27 18:27:39 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", type=").append(type);
        sb.append(", verificationType=").append(verificationType);
        sb.append(", ctime=").append(ctime);
        sb.append(", status=").append(status);
        sb.append(", signature=").append(signature);
        sb.append("]");
        return sb.toString();
    }
}