package tw.gov.ndc.emsg.mydata.entity;

import java.io.Serializable;
import java.util.Date;

public class Verify implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column verify.id
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column verify.key
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	private String key;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column verify.ctime
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	private Date ctime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column verify.uid
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column verify.birthdate
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	private Date birthdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column verify.check_level
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	private String checkLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column verify.scope
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	private String scope;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table verify
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */

	private String multifactorType;

	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column verify.id
	 * @return  the value of verify.id
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column verify.id
	 * @param id  the value for verify.id
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column verify.key
	 * @return  the value of verify.key
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public String getKey() {
		return key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column verify.key
	 * @param key  the value for verify.key
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public void setKey(String key) {
		this.key = key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column verify.ctime
	 * @return  the value of verify.ctime
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public Date getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column verify.ctime
	 * @param ctime  the value for verify.ctime
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column verify.uid
	 * @return  the value of verify.uid
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column verify.uid
	 * @param uid  the value for verify.uid
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column verify.birthdate
	 * @return  the value of verify.birthdate
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public Date getBirthdate() {
		return birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column verify.birthdate
	 * @param birthdate  the value for verify.birthdate
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column verify.check_level
	 * @return  the value of verify.check_level
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public String getCheckLevel() {
		return checkLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column verify.check_level
	 * @param checkLevel  the value for verify.check_level
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public void setCheckLevel(String checkLevel) {
		this.checkLevel = checkLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column verify.scope
	 * @return  the value of verify.scope
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public String getScope() {
		return scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column verify.scope
	 * @param scope  the value for verify.scope
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */
	public void setScope(String scope) {
		this.scope = scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table verify
	 * @mbg.generated  Tue Feb 11 15:12:01 CST 2020
	 */

	public String getMultifactorType() {
		return multifactorType;
	}

	public void setMultifactorType(String multifactorType) {
		this.multifactorType = multifactorType;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", key=").append(key);
		sb.append(", ctime=").append(ctime);
		sb.append(", uid=").append(uid);
		sb.append(", birthdate=").append(birthdate);
		sb.append(", checkLevel=").append(checkLevel);
		sb.append(", scope=").append(scope);
		sb.append("]");
		return sb.toString();
	}
}